#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id$'
    short_opts="i:hqv"
    long_opts="interface,help,quiet,verbose,version"

    iface=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Get address of the gateway (ADSL Router)"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTIONS]"
    echo
    echo "Options: "
    echo "    -i, --iface=IF-NAME     specify the interface"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -i|--iface)
            iface=$2;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ -z "$iface" ]; then
        read iface __ < <(ifconfig)
    fi

    while read dest gw mask flags metric ref use _iface xxx; do
        if [ "$dest" = 0.0.0.0 ]; then
            if [ "$iface" = "$_iface" ]; then
                echo "$gw"
                exit 0
            fi
        fi
    done < <(route -n)

    exit 1
}

boot "$@"
