#!/bin/bash
    : ${RCSID:=$Id: - @VERSION@ @DATE@ @TIME@ - $}
    : ${PROGRAM_TITLE:=Auto fix file modes by extension}
    : ${PROGRAM_SYNTAX:=[OPTIONS] [--] FILES}
    
    . shlib-import cliboot
    option -R --recursive   "Change files and directories recursively"
    option -q --quiet       "Repeat to get less info"
    option -v --verbose     "Repeat to get more info"
    option -h --help        "Show this help page"
    option    --version     "Print the version info"

    recursive=

function setopt() {
    case "$1" in
        -R|--recursive)
            recursive=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    opts=()
    [ "$recursive" = 1 ] && opts=("${opts[@]}" -R)

    for f in "$@"; do
        chmod "${opts[@]}" go-w,+w "$f"
        find "$f" -type f -exec chmod -x {} +
        for e in com exe bat cmd msi; do
            find "$f" -name "*.$e" -exec chmod +x {} +
        done
    done
}

boot "$@"
