#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 2141 2010-12-13 06:15:26Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Mount a file image by loop device"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FILES"
    echo
    echo "Options: "
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    err=0
    fs=auto

    for file in "$@"; do
        if [ ! -r "$file" ]; then
            echo "File $file isn't readable. " >&2
            exit 1
        fi
        autodir="${file%.*}"
        if [ "$autodir" = "$file" ]; then
            autodir="$file..mnt"
        fi

        case "${file##*.}" in
            zip) echo "Zip fs isn't supported. "; exit 1;;
            ext2) fs=ext2;;
            ext3) fs=ext3;;
            ext4) fs=ext4;;
            ntfs) fs=ntfs;;
            squashfs) fs=squashfs;;
            vfat) fs=vfat;;
        esac

        _log1 "Mount $fs:${file##*/} at $autodir"

        if [ ! -d "$autodir" ]; then
            if ! mkdir -p "$autodir"; then
                echo "Can't create mount point $autodir" >&2
                exit 1
            fi
        fi
        if ! mount -o loop -t $fs "$file" "$autodir/"; then
            echo "Failed to mount $file" >&2
            err=1
        fi
    done

    exit $err
}

boot "$@"
