.\"
.\"
.\" grepurl.man - grepurl manpage
.\" Copyright (C) 2010 Lenik (谢继雷)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH GREPURL 1
.SH NAME
grepurl \- Grep and concat URLs with start-url
.SH SYNOPSIS
.B grepurl
PATTERN START-URL
.SH DESCRIPTION
Grep and concat URLs with start-url

.SH EXAMPLES

.B
grepurl -Em1 '[^"]+\.war' http://www.apache.org/dyn/closer.cgi/archiva/binaries/apache-archiva-1.3.1.war

.PP
Grep the first .war href in the specified page.

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Lenik <lenik at bodz.net>
.br
