#!/bin/bash
    : ${RCSID:=$Id: - @VERSION@ @DATE@ @TIME@ - $}
    : ${PROGRAM_TITLE:="uni/ scan & maintainance utility"}
    : ${PROGRAM_SYNTAX:=[OPTIONS] [--] CMD ...}

    . shlib-import cliboot
    option -q --quiet       "Repeat to get less info"
    option -v --verbose     "Repeat to get more info"
    option -h --help        "Show this help page"
    option    --version     "Print the version info"

function help_more() {
    echo
    echo "Command: "
    echo "    notags                  List package dirs without tags file"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    cmd="$1"
    shift

    $cmd "$@"

    echo Done.
}

function notags() {
    find -name debian -type d | while read dir; do
        if [ -f "$dir/tags" ]; then
            :;
        else
            echo $dir
        fi
    done
}

boot "$@"
