alias as='aptitude search'
alias sagi='sudo apt-get install --allow-unauthenticated'
alias sagu='sudo apt-get remove'
alias sagp='sudo apt-get purge'
alias sagr='sudo apt-get-reinstall2'
alias sagc='sudo apt-get autoclean'
alias sau='sudo apt-get update; sudo apt-get dist-upgrade --allow-unauthenticated'
