#!/bin/bash

if [ ! -f VERSION.av ]; then
    echo "Not an autover dir. "
    exit 1
fi

if [ `vcscmd slist | wc -l` = 0 ]; then
    echo "already updated"
    exit 0
fi

if vcscmd slist VERSION.av | grep VERSION.av | grep -q '^M'; then
    echo "Version is already increased. "
else
    if vcscmd slist | grep -q '^[AD]'; then
        echo "Detected minor-level changes"
        vercomp -i minor >/dev/null
    else
        vercomp -i commit >/dev/null
    fi
    vcscmd add VERSION.av 2>/dev/null
fi

[ -f configure.ac ] && autover

if ! deb-redist -i; then
    echo debuild/redist failed.
    exit 1
fi

# don't update/commit in batch-mode.
if [ "$1" != "-b" ]; then
    sudo aptitude update
    # sudo apt-get update

    if ! sudo apt-get dist-upgrade --allow-unauthenticated; then
        echo "dist-upgrade failed, canceled. "
        exit 1
    fi

    vcscmd commit
fi

