#!/bin/bash

# VCMD is a program need the version number in the working dir name.
# VCMD is constructed by calling program with suffix _ver stripped.

# vexec rename current dir to DIR_VERSION, then run VCMD,
# at last restore the dir name before exit.

VCMD="${0%_ver}"
if [ "$VCMD" = "$0" ]; then
    echo "The calling program must end with _ver"
    exit 1
fi
if [ ! -x "$VCMD" ]; then
    VCMD="${VCMD##*/}"
fi

dir=`readlink -f .`
dirbase="${dir##*/}"

ver=`vercomp`

basever="$dirbase-$ver"

tmpdir=/tmp/verexec$$.$RANDOM
rm -fR $tmpdir
mkdir -p $tmpdir

cd $tmpdir
ln -s "$dir" $basever
cd $basever

$VCMD "$@"
err=$?

# cd $tmpdir
# rm -f $basever
cd "$dir"
rm -fR $tmpdir

exit $err
