#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id$'
    short_opts="s:whqv"
    long_opts="host:,wait,help,quiet,verbose,version"

    hosts=()
    wait=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Resolve host to local locally"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] CMD ARGS"
    echo
    echo "Options: "
    echo "    -s, --host=HOST         add HOST to local list"
    echo "    -w, --wait              wait before exit, used for async cmds"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -s|--host)
            hosts[${#hosts[@]}]="$2";;
        -w|--wait)
            wait=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    session=Session-$$-$RANDOM
    count=0

    _log2 "Config /etc/hosts"
    for h in "${hosts[@]}"; do
        sudo lineconf -t /etc/hosts $session.$count \
            "127.0.0.1 $h"
        ((count++))
    done

    _log2 "Run user command"
    "$@"

    if [ "$wait" = 1 ]; then
        read -p "Press enter to unconfig... "
    fi

    _log2 "Unconfig /etc/hosts"
    for ((i = 0; i < count; i++)); do
        sudo lineconf -kt /etc/hosts $session.$i
    done
}

boot "$@"
