#!/bin/bash

# Workarounds for:
#       Temporary file remove/create fix
#       Temporary file rename/restore fix
#       Shell interpretor: Text file busy fix
sleepenh 0.01 >/dev/null

_file="$1"
if [ ! -e "$_file" ]; then
    # caused by temporary removing maybe.
    exit 1
fi

_date=`stat -c%Y "$_file"`
if [ "$_date" = "$2" ]; then
    exit 1
fi
_ver="$3"
shift 3

_pad='------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'

_cols=`tput cols`
_title="[42mFile Version[47m $_ver[m"
_ntitle=$(( ${#_title} + 2 - 13 ))
_halfpad=$(( (_cols - _ntitle) / 2 ))
_line="${_pad:0:_halfpad} $_title ${_pad:0:_cols - _ntitle - _halfpad}"
echo "$_line"

"$@"

echo "${_pad:0:_cols}"

exit 0
