#!/usr/bin/env perl

use strict;
use warnings;
use cmt::subst;
use Getopt::Long;
    Getopt::Long::Configure('gnu_getopt');

GetOptions('color|c!' => \$opt_color);

subst_init();

while (<>) {
    my $a = rsubst($_);
    print $a;
}
