*amd64*
*powerpc*
*sparc*
*-dbg_*
linux-source-*

dists/dapper*/
dists/feisty*/
dists/gutsy*/
dists/hardy*/
dists/intrepid*/
dists/jaunty*/

eclipse*/
universe/g/gcc-*/
glassfish*/

alien-arena/
alien-arena-data/
glest/
glest-data/
sauerbraten/
sauerbraten-data/
sauerbraten-wake6/
tremulous/
tremulous-data/

beneath-a-steel-sky/
fgfs-atlas/
fgfs-base/
fillets-ng/
fillets-ng-data/
flight-of-the-amazon-queen/
freeciv/
freedroid/
freedroidrpg/
frozen-bubble/
libxmpp4r-ruby/
lincity/
lincity-ng/
nexuiz/
nexuiz-data/
openarena/
openarena-data/
vegastrike/
vegastrike-data/
vegastrike-music/
warzone2100/
warzone2100-music/
wesnoth/
wormux/

scorched3d/
warsow/
warsow-data/

kde-i18n-af/
kde-i18n-ar/
kde-i18n-az/
kde-i18n-be/
kde-i18n-bg/
kde-i18n-bn/
kde-i18n-br/
kde-i18n-bs/
kde-i18n-ca/
kde-i18n-cs/
kde-i18n-csb/
kde-i18n-cy/
kde-i18n-da/
kde-i18n-el/
kde-i18n-eo/
kde-i18n-eu/
kde-i18n-fa/
kde-i18n-fi/
kde-i18n-fy/
kde-i18n-ga/
kde-i18n-gl/
kde-i18n-he/
kde-i18n-hi/
kde-i18n-hr/
kde-i18n-hsb/
kde-i18n-hu/
kde-i18n-is/
kde-i18n-it/
kde-i18n-kk/
kde-i18n-km/
kde-i18n-lt/
kde-i18n-lv/
kde-i18n-mk/
kde-i18n-mn/
kde-i18n-ms/
kde-i18n-nb/
kde-i18n-nds/
kde-i18n-nl/
kde-i18n-nn/
kde-i18n-pa/
kde-i18n-pl/
kde-i18n-pt/
kde-i18n-ptbr/
kde-i18n-ro/
kde-i18n-rw/
kde-i18n-se/
kde-i18n-sk/
kde-i18n-sl/
kde-i18n-sr/
kde-i18n-srlatn/
kde-i18n-ss/
kde-i18n-sv/
kde-i18n-ta/
kde-i18n-te/
kde-i18n-tg/
kde-i18n-th/
kde-i18n-tr/
kde-i18n-uk/
kde-i18n-uz/
kde-i18n-vi/
kde-i18n-wa/
kde-l10n-ar/
kde-l10n-be/
kde-l10n-bg/
kde-l10n-ca/
kde-l10n-cs/
kde-l10n-csb/
kde-l10n-da/
kde-l10n-el/
kde-l10n-eo/
kde-l10n-eu/
kde-l10n-fa/
kde-l10n-fi/
kde-l10n-fy/
kde-l10n-ga/
kde-l10n-gl/
kde-l10n-gu/
kde-l10n-he/
kde-l10n-hi/
kde-l10n-hu/
kde-l10n-is/
kde-l10n-it/
kde-l10n-kk/
kde-l10n-km/
kde-l10n-kn/
kde-l10n-ku/
kde-l10n-lt/
kde-l10n-lv/
kde-l10n-mai/
kde-l10n-mk/
kde-l10n-ml/
kde-l10n-mr/
kde-l10n-nb/
kde-l10n-nds/
kde-l10n-ne/
kde-l10n-nl/
kde-l10n-nn/
kde-l10n-pa/
kde-l10n-pl/
kde-l10n-pt/
kde-l10n-ptbr/
kde-l10n-ro/
kde-l10n-se/
kde-l10n-sl/
kde-l10n-sr/
kde-l10n-sv/
kde-l10n-ta/
kde-l10n-tg/
kde-l10n-th/
kde-l10n-tr/
kde-l10n-uk/
kde-l10n-wa/

language-pack-aa/
language-pack-aa-base/
language-pack-ace/
language-pack-ace-base/
language-pack-af/
language-pack-af-base/
language-pack-am/
language-pack-am-base/
language-pack-an/
language-pack-an-base/
language-pack-ar/
language-pack-ar-base/
language-pack-as/
language-pack-as-base/
language-pack-ast/
language-pack-ast-base/
language-pack-az/
language-pack-az-base/
language-pack-be/
language-pack-be-base/
language-pack-ber/
language-pack-ber-base/
language-pack-bg/
language-pack-bg-base/
language-pack-bho/
language-pack-bho-base/
language-pack-bn/
language-pack-bn-base/
language-pack-bo/
language-pack-bo-base/
language-pack-br/
language-pack-br-base/
language-pack-bs/
language-pack-bs-base/
language-pack-bua/
language-pack-bua-base/
language-pack-byn/
language-pack-byn-base/
language-pack-ca/
language-pack-ca-base/
language-pack-ceb/
language-pack-ceb-base/
language-pack-co/
language-pack-co-base/
language-pack-crh/
language-pack-crh-base/
language-pack-cs/
language-pack-cs-base/
language-pack-csb/
language-pack-csb-base/
language-pack-cv/
language-pack-cv-base/
language-pack-cy/
language-pack-cy-base/
language-pack-da/
language-pack-da-base/
language-pack-dsb/
language-pack-dsb-base/
language-pack-dv/
language-pack-dv-base/
language-pack-dz/
language-pack-dz-base/
language-pack-el/
language-pack-el-base/
language-pack-eo/
language-pack-eo-base/
language-pack-eu/
language-pack-eu-base/
language-pack-fa/
language-pack-fa-base/
language-pack-fi/
language-pack-fi-base/
language-pack-fil/
language-pack-fil-base/
language-pack-fo/
language-pack-fo-base/
language-pack-frm/
language-pack-frm-base/
language-pack-fur/
language-pack-fur-base/
language-pack-fy/
language-pack-fy-base/
language-pack-ga/
language-pack-ga-base/
language-pack-gd/
language-pack-gd-base/
language-pack-gl/
language-pack-gl-base/
language-pack-gn/
language-pack-gn-base/
language-pack-gnome-aa/
language-pack-gnome-aa-base/
language-pack-gnome-ace/
language-pack-gnome-ace-base/
language-pack-gnome-af/
language-pack-gnome-af-base/
language-pack-gnome-ak/
language-pack-gnome-ak-base/
language-pack-gnome-am/
language-pack-gnome-am-base/
language-pack-gnome-an/
language-pack-gnome-an-base/
language-pack-gnome-ang/
language-pack-gnome-ang-base/
language-pack-gnome-ar/
language-pack-gnome-ar-base/
language-pack-gnome-as/
language-pack-gnome-as-base/
language-pack-gnome-ast/
language-pack-gnome-ast-base/
language-pack-gnome-az/
language-pack-gnome-az-base/
language-pack-gnome-bal/
language-pack-gnome-bal-base/
language-pack-gnome-be/
language-pack-gnome-be-base/
language-pack-gnome-ber/
language-pack-gnome-ber-base/
language-pack-gnome-bg/
language-pack-gnome-bg-base/
language-pack-gnome-bn/
language-pack-gnome-bn-base/
language-pack-gnome-br/
language-pack-gnome-br-base/
language-pack-gnome-bs/
language-pack-gnome-bs-base/
language-pack-gnome-ca/
language-pack-gnome-ca-base/
language-pack-gnome-ceb/
language-pack-gnome-ceb-base/
language-pack-gnome-co/
language-pack-gnome-co-base/
language-pack-gnome-crh/
language-pack-gnome-crh-base/
language-pack-gnome-cs/
language-pack-gnome-cs-base/
language-pack-gnome-csb/
language-pack-gnome-csb-base/
language-pack-gnome-cv/
language-pack-gnome-cv-base/
language-pack-gnome-cy/
language-pack-gnome-cy-base/
language-pack-gnome-da/
language-pack-gnome-da-base/
language-pack-gnome-dsb/
language-pack-gnome-dsb-base/
language-pack-gnome-dv/
language-pack-gnome-dv-base/
language-pack-gnome-dz/
language-pack-gnome-dz-base/
language-pack-gnome-el/
language-pack-gnome-el-base/
language-pack-gnome-eo/
language-pack-gnome-eo-base/
language-pack-gnome-eu/
language-pack-gnome-eu-base/
language-pack-gnome-fa/
language-pack-gnome-fa-base/
language-pack-gnome-fi/
language-pack-gnome-fi-base/
language-pack-gnome-fil/
language-pack-gnome-fil-base/
language-pack-gnome-fo/
language-pack-gnome-fo-base/
language-pack-gnome-frm/
language-pack-gnome-frm-base/
language-pack-gnome-fur/
language-pack-gnome-fur-base/
language-pack-gnome-fy/
language-pack-gnome-fy-base/
language-pack-gnome-ga/
language-pack-gnome-ga-base/
language-pack-gnome-gd/
language-pack-gnome-gd-base/
language-pack-gnome-gl/
language-pack-gnome-gl-base/
language-pack-gnome-gn/
language-pack-gnome-gn-base/
language-pack-gnome-gu/
language-pack-gnome-gu-base/
language-pack-gnome-ha/
language-pack-gnome-ha-base/
language-pack-gnome-he/
language-pack-gnome-he-base/
language-pack-gnome-hi/
language-pack-gnome-hi-base/
language-pack-gnome-hil/
language-pack-gnome-hil-base/
language-pack-gnome-hr/
language-pack-gnome-hr-base/
language-pack-gnome-ht/
language-pack-gnome-ht-base/
language-pack-gnome-hu/
language-pack-gnome-hu-base/
language-pack-gnome-hy/
language-pack-gnome-hy-base/
language-pack-gnome-ia/
language-pack-gnome-ia-base/
language-pack-gnome-id/
language-pack-gnome-id-base/
language-pack-gnome-ig/
language-pack-gnome-ig-base/
language-pack-gnome-io/
language-pack-gnome-io-base/
language-pack-gnome-is/
language-pack-gnome-is-base/
language-pack-gnome-it/
language-pack-gnome-it-base/
language-pack-gnome-jbo/
language-pack-gnome-jbo-base/
language-pack-gnome-jv/
language-pack-gnome-jv-base/
language-pack-gnome-ka/
language-pack-gnome-ka-base/
language-pack-gnome-kk/
language-pack-gnome-kk-base/
language-pack-gnome-km/
language-pack-gnome-km-base/
language-pack-gnome-kn/
language-pack-gnome-kn-base/
language-pack-gnome-kok/
language-pack-gnome-kok-base/
language-pack-gnome-ks/
language-pack-gnome-ks-base/
language-pack-gnome-ku/
language-pack-gnome-ku-base/
language-pack-gnome-kw/
language-pack-gnome-kw-base/
language-pack-gnome-ky/
language-pack-gnome-ky-base/
language-pack-gnome-la/
language-pack-gnome-la-base/
language-pack-gnome-lb/
language-pack-gnome-lb-base/
language-pack-gnome-lg/
language-pack-gnome-lg-base/
language-pack-gnome-li/
language-pack-gnome-li-base/
language-pack-gnome-ln/
language-pack-gnome-ln-base/
language-pack-gnome-lo/
language-pack-gnome-lo-base/
language-pack-gnome-lt/
language-pack-gnome-lt-base/
language-pack-gnome-lv/
language-pack-gnome-lv-base/
language-pack-gnome-mai/
language-pack-gnome-mai-base/
language-pack-gnome-mg/
language-pack-gnome-mg-base/
language-pack-gnome-mh/
language-pack-gnome-mh-base/
language-pack-gnome-mi/
language-pack-gnome-mi-base/
language-pack-gnome-mk/
language-pack-gnome-mk-base/
language-pack-gnome-ml/
language-pack-gnome-ml-base/
language-pack-gnome-mn/
language-pack-gnome-mn-base/
language-pack-gnome-mr/
language-pack-gnome-mr-base/
language-pack-gnome-ms/
language-pack-gnome-ms-base/
language-pack-gnome-mt/
language-pack-gnome-mt-base/
language-pack-gnome-mus/
language-pack-gnome-mus-base/
language-pack-gnome-my/
language-pack-gnome-my-base/
language-pack-gnome-nb/
language-pack-gnome-nb-base/
language-pack-gnome-nds/
language-pack-gnome-nds-base/
language-pack-gnome-ne/
language-pack-gnome-ne-base/
language-pack-gnome-nl/
language-pack-gnome-nl-base/
language-pack-gnome-nn/
language-pack-gnome-nn-base/
language-pack-gnome-no/
language-pack-gnome-no-base/
language-pack-gnome-nso/
language-pack-gnome-nso-base/
language-pack-gnome-oc/
language-pack-gnome-oc-base/
language-pack-gnome-om/
language-pack-gnome-om-base/
language-pack-gnome-or/
language-pack-gnome-or-base/
language-pack-gnome-pa/
language-pack-gnome-pa-base/
language-pack-gnome-pap/
language-pack-gnome-pap-base/
language-pack-gnome-pl/
language-pack-gnome-pl-base/
language-pack-gnome-ps/
language-pack-gnome-ps-base/
language-pack-gnome-pt/
language-pack-gnome-pt-base/
language-pack-gnome-qu/
language-pack-gnome-qu-base/
language-pack-gnome-rm/
language-pack-gnome-rm-base/
language-pack-gnome-ro/
language-pack-gnome-ro-base/
language-pack-gnome-rom/
language-pack-gnome-rom-base/
language-pack-gnome-rw/
language-pack-gnome-rw-base/
language-pack-gnome-sa/
language-pack-gnome-sa-base/
language-pack-gnome-sc/
language-pack-gnome-sc-base/
language-pack-gnome-sco/
language-pack-gnome-sco-base/
language-pack-gnome-sd/
language-pack-gnome-sd-base/
language-pack-gnome-se/
language-pack-gnome-se-base/
language-pack-gnome-shs/
language-pack-gnome-shs-base/
language-pack-gnome-si/
language-pack-gnome-si-base/
language-pack-gnome-sk/
language-pack-gnome-sk-base/
language-pack-gnome-sl/
language-pack-gnome-sl-base/
language-pack-gnome-sn/
language-pack-gnome-sn-base/
language-pack-gnome-so/
language-pack-gnome-so-base/
language-pack-gnome-sq/
language-pack-gnome-sq-base/
language-pack-gnome-sr/
language-pack-gnome-sr-base/
language-pack-gnome-st/
language-pack-gnome-st-base/
language-pack-gnome-sv/
language-pack-gnome-sv-base/
language-pack-gnome-sw/
language-pack-gnome-sw-base/
language-pack-gnome-syr/
language-pack-gnome-syr-base/
language-pack-gnome-ta/
language-pack-gnome-ta-base/
language-pack-gnome-te/
language-pack-gnome-te-base/
language-pack-gnome-tet/
language-pack-gnome-tet-base/
language-pack-gnome-tg/
language-pack-gnome-tg-base/
language-pack-gnome-th/
language-pack-gnome-th-base/
language-pack-gnome-ti/
language-pack-gnome-ti-base/
language-pack-gnome-tk/
language-pack-gnome-tk-base/
language-pack-gnome-tl/
language-pack-gnome-tl-base/
language-pack-gnome-tlh/
language-pack-gnome-tlh-base/
language-pack-gnome-tr/
language-pack-gnome-tr-base/
language-pack-gnome-ts/
language-pack-gnome-ts-base/
language-pack-gnome-tt/
language-pack-gnome-tt-base/
language-pack-gnome-ug/
language-pack-gnome-ug-base/
language-pack-gnome-uk/
language-pack-gnome-uk-base/
language-pack-gnome-ur/
language-pack-gnome-ur-base/
language-pack-gnome-uz/
language-pack-gnome-uz-base/
language-pack-gnome-ve/
language-pack-gnome-ve-base/
language-pack-gnome-vi/
language-pack-gnome-vi-base/
language-pack-gnome-wa/
language-pack-gnome-wa-base/
language-pack-gnome-wo/
language-pack-gnome-wo-base/
language-pack-gnome-xh/
language-pack-gnome-xh-base/
language-pack-gnome-yi/
language-pack-gnome-yi-base/
language-pack-gnome-yo/
language-pack-gnome-yo-base/
language-pack-gnome-zu/
language-pack-gnome-zu-base/
language-pack-gnome-zza/
language-pack-gnome-zza-base/
language-pack-grc/
language-pack-grc-base/
language-pack-gu/
language-pack-gu-base/
language-pack-haw/
language-pack-haw-base/
language-pack-he/
language-pack-he-base/
language-pack-hi/
language-pack-hi-base/
language-pack-hil/
language-pack-hil-base/
language-pack-hr/
language-pack-hr-base/
language-pack-hsb/
language-pack-hsb-base/
language-pack-ht/
language-pack-ht-base/
language-pack-hu/
language-pack-hu-base/
language-pack-hy/
language-pack-hy-base/
language-pack-ia/
language-pack-ia-base/
language-pack-id/
language-pack-id-base/
language-pack-io/
language-pack-io-base/
language-pack-is/
language-pack-is-base/
language-pack-it/
language-pack-it-base/
language-pack-jbo/
language-pack-jbo-base/
language-pack-jv/
language-pack-jv-base/
language-pack-ka/
language-pack-ka-base/
language-pack-kab/
language-pack-kab-base/
language-pack-kbd/
language-pack-kbd-base/
language-pack-kde-aa/
language-pack-kde-aa-base/
language-pack-kde-ace/
language-pack-kde-ace-base/
language-pack-kde-af/
language-pack-kde-af-base/
language-pack-kde-ak/
language-pack-kde-ak-base/
language-pack-kde-am/
language-pack-kde-am-base/
language-pack-kde-an/
language-pack-kde-an-base/
language-pack-kde-ar/
language-pack-kde-ar-base/
language-pack-kde-as/
language-pack-kde-as-base/
language-pack-kde-ast/
language-pack-kde-ast-base/
language-pack-kde-ay/
language-pack-kde-ay-base/
language-pack-kde-az/
language-pack-kde-az-base/
language-pack-kde-be/
language-pack-kde-be-base/
language-pack-kde-bg/
language-pack-kde-bg-base/
language-pack-kde-bn/
language-pack-kde-bn-base/
language-pack-kde-br/
language-pack-kde-br-base/
language-pack-kde-bs/
language-pack-kde-bs-base/
language-pack-kde-ca/
language-pack-kde-ca-base/
language-pack-kde-ceb/
language-pack-kde-ceb-base/
language-pack-kde-co/
language-pack-kde-co-base/
language-pack-kde-cs/
language-pack-kde-cs-base/
language-pack-kde-csb/
language-pack-kde-csb-base/
language-pack-kde-cy/
language-pack-kde-cy-base/
language-pack-kde-da/
language-pack-kde-da-base/
language-pack-kde-dsb/
language-pack-kde-dsb-base/
language-pack-kde-dz/
language-pack-kde-dz-base/
language-pack-kde-el/
language-pack-kde-el-base/
language-pack-kde-eo/
language-pack-kde-eo-base/
language-pack-kde-eu/
language-pack-kde-eu-base/
language-pack-kde-fa/
language-pack-kde-fa-base/
language-pack-kde-fi/
language-pack-kde-fi-base/
language-pack-kde-fil/
language-pack-kde-fil-base/
language-pack-kde-fo/
language-pack-kde-fo-base/
language-pack-kde-fur/
language-pack-kde-fur-base/
language-pack-kde-fy/
language-pack-kde-fy-base/
language-pack-kde-ga/
language-pack-kde-ga-base/
language-pack-kde-gd/
language-pack-kde-gd-base/
language-pack-kde-gl/
language-pack-kde-gl-base/
language-pack-kde-gu/
language-pack-kde-gu-base/
language-pack-kde-he/
language-pack-kde-he-base/
language-pack-kde-hi/
language-pack-kde-hi-base/
language-pack-kde-hil/
language-pack-kde-hil-base/
language-pack-kde-hr/
language-pack-kde-hr-base/
language-pack-kde-hsb/
language-pack-kde-hsb-base/
language-pack-kde-ht/
language-pack-kde-ht-base/
language-pack-kde-hu/
language-pack-kde-hu-base/
language-pack-kde-hy/
language-pack-kde-hy-base/
language-pack-kde-ia/
language-pack-kde-ia-base/
language-pack-kde-id/
language-pack-kde-id-base/
language-pack-kde-is/
language-pack-kde-is-base/
language-pack-kde-it/
language-pack-kde-it-base/
language-pack-kde-jbo/
language-pack-kde-jbo-base/
language-pack-kde-jv/
language-pack-kde-jv-base/
language-pack-kde-ka/
language-pack-kde-ka-base/
language-pack-kde-kab/
language-pack-kde-kab-base/
language-pack-kde-kk/
language-pack-kde-kk-base/
language-pack-kde-kl/
language-pack-kde-kl-base/
language-pack-kde-km/
language-pack-kde-km-base/
language-pack-kde-kn/
language-pack-kde-kn-base/
language-pack-kde-ku/
language-pack-kde-ku-base/
language-pack-kde-kw/
language-pack-kde-kw-base/
language-pack-kde-ky/
language-pack-kde-ky-base/
language-pack-kde-la/
language-pack-kde-la-base/
language-pack-kde-lb/
language-pack-kde-lb-base/
language-pack-kde-li/
language-pack-kde-li-base/
language-pack-kde-ln/
language-pack-kde-ln-base/
language-pack-kde-lo/
language-pack-kde-lo-base/
language-pack-kde-lt/
language-pack-kde-lt-base/
language-pack-kde-lv/
language-pack-kde-lv-base/
language-pack-kde-mai/
language-pack-kde-mai-base/
language-pack-kde-mg/
language-pack-kde-mg-base/
language-pack-kde-mi/
language-pack-kde-mi-base/
language-pack-kde-mk/
language-pack-kde-mk-base/
language-pack-kde-ml/
language-pack-kde-ml-base/
language-pack-kde-mn/
language-pack-kde-mn-base/
language-pack-kde-mr/
language-pack-kde-mr-base/
language-pack-kde-ms/
language-pack-kde-ms-base/
language-pack-kde-mt/
language-pack-kde-mt-base/
language-pack-kde-mus/
language-pack-kde-mus-base/
language-pack-kde-my/
language-pack-kde-my-base/
language-pack-kde-nap/
language-pack-kde-nap-base/
language-pack-kde-nb/
language-pack-kde-nb-base/
language-pack-kde-nds/
language-pack-kde-nds-base/
language-pack-kde-ne/
language-pack-kde-ne-base/
language-pack-kde-nl/
language-pack-kde-nl-base/
language-pack-kde-nn/
language-pack-kde-nn-base/
language-pack-kde-no/
language-pack-kde-no-base/
language-pack-kde-nso/
language-pack-kde-nso-base/
language-pack-kde-nv/
language-pack-kde-nv-base/
language-pack-kde-oc/
language-pack-kde-oc-base/
language-pack-kde-om/
language-pack-kde-om-base/
language-pack-kde-pa/
language-pack-kde-pa-base/
language-pack-kde-pam/
language-pack-kde-pam-base/
language-pack-kde-pl/
language-pack-kde-pl-base/
language-pack-kde-ps/
language-pack-kde-ps-base/
language-pack-kde-pt/
language-pack-kde-pt-base/
language-pack-kde-qu/
language-pack-kde-qu-base/
language-pack-kde-ro/
language-pack-kde-ro-base/
language-pack-kde-rom/
language-pack-kde-rom-base/
language-pack-kde-rw/
language-pack-kde-rw-base/
language-pack-kde-sc/
language-pack-kde-sc-base/
language-pack-kde-sco/
language-pack-kde-sco-base/
language-pack-kde-sd/
language-pack-kde-sd-base/
language-pack-kde-se/
language-pack-kde-se-base/
language-pack-kde-shs/
language-pack-kde-shs-base/
language-pack-kde-si/
language-pack-kde-si-base/
language-pack-kde-sk/
language-pack-kde-sk-base/
language-pack-kde-sl/
language-pack-kde-sl-base/
language-pack-kde-so/
language-pack-kde-so-base/
language-pack-kde-sq/
language-pack-kde-sq-base/
language-pack-kde-sr/
language-pack-kde-sr-base/
language-pack-kde-ss/
language-pack-kde-ss-base/
language-pack-kde-sv/
language-pack-kde-sv-base/
language-pack-kde-sw/
language-pack-kde-sw-base/
language-pack-kde-syr/
language-pack-kde-syr-base/
language-pack-kde-ta/
language-pack-kde-ta-base/
language-pack-kde-te/
language-pack-kde-te-base/
language-pack-kde-tg/
language-pack-kde-tg-base/
language-pack-kde-th/
language-pack-kde-th-base/
language-pack-kde-ti/
language-pack-kde-ti-base/
language-pack-kde-tl/
language-pack-kde-tl-base/
language-pack-kde-tlh/
language-pack-kde-tlh-base/
language-pack-kde-tmh/
language-pack-kde-tmh-base/
language-pack-kde-tr/
language-pack-kde-tr-base/
language-pack-kde-ts/
language-pack-kde-ts-base/
language-pack-kde-tt/
language-pack-kde-tt-base/
language-pack-kde-ug/
language-pack-kde-ug-base/
language-pack-kde-uk/
language-pack-kde-uk-base/
language-pack-kde-ur/
language-pack-kde-ur-base/
language-pack-kde-uz/
language-pack-kde-uz-base/
language-pack-kde-ve/
language-pack-kde-ve-base/
language-pack-kde-vi/
language-pack-kde-vi-base/
language-pack-kde-wa/
language-pack-kde-wa-base/
language-pack-kde-wo/
language-pack-kde-wo-base/
language-pack-kde-xh/
language-pack-kde-xh-base/
language-pack-kde-yi/
language-pack-kde-yi-base/
language-pack-kde-yo/
language-pack-kde-yo-base/
language-pack-kde-zu/
language-pack-kde-zu-base/
language-pack-kde-zza/
language-pack-kde-zza-base/
language-pack-kk/
language-pack-kk-base/
language-pack-km/
language-pack-km-base/
language-pack-kn/
language-pack-kn-base/
language-pack-ku/
language-pack-ku-base/
language-pack-kw/
language-pack-kw-base/
language-pack-ky/
language-pack-ky-base/
language-pack-la/
language-pack-la-base/
language-pack-lb/
language-pack-lb-base/
language-pack-lg/
language-pack-lg-base/
language-pack-li/
language-pack-li-base/
language-pack-ln/
language-pack-ln-base/
language-pack-lo/
language-pack-lo-base/
language-pack-lt/
language-pack-lt-base/
language-pack-lv/
language-pack-lv-base/
language-pack-mg/
language-pack-mg-base/
language-pack-mi/
language-pack-mi-base/
language-pack-mk/
language-pack-mk-base/
language-pack-ml/
language-pack-ml-base/
language-pack-mn/
language-pack-mn-base/
language-pack-mr/
language-pack-mr-base/
language-pack-ms/
language-pack-ms-base/
language-pack-mt/
language-pack-mt-base/
language-pack-mus/
language-pack-mus-base/
language-pack-my/
language-pack-my-base/
language-pack-nap/
language-pack-nap-base/
language-pack-nb/
language-pack-nb-base/
language-pack-nds/
language-pack-nds-base/
language-pack-ne/
language-pack-ne-base/
language-pack-nl/
language-pack-nl-base/
language-pack-nn/
language-pack-nn-base/
language-pack-no/
language-pack-no-base/
language-pack-nr/
language-pack-nr-base/
language-pack-nso/
language-pack-nso-base/
language-pack-oc/
language-pack-oc-base/
language-pack-oj/
language-pack-oj-base/
language-pack-om/
language-pack-om-base/
language-pack-or/
language-pack-or-base/
language-pack-pa/
language-pack-pa-base/
language-pack-pl/
language-pack-pl-base/
language-pack-ps/
language-pack-ps-base/
language-pack-pt/
language-pack-pt-base/
language-pack-qu/
language-pack-qu-base/
language-pack-rm/
language-pack-rm-base/
language-pack-ro/
language-pack-ro-base/
language-pack-rw/
language-pack-rw-base/
language-pack-sc/
language-pack-sc-base/
language-pack-sco/
language-pack-sco-base/
language-pack-sd/
language-pack-sd-base/
language-pack-se/
language-pack-se-base/
language-pack-si/
language-pack-si-base/
language-pack-sk/
language-pack-sk-base/
language-pack-sl/
language-pack-sl-base/
language-pack-sn/
language-pack-sn-base/
language-pack-so/
language-pack-so-base/
language-pack-sq/
language-pack-sq-base/
language-pack-sr/
language-pack-sr-base/
language-pack-st/
language-pack-st-base/
language-pack-sv/
language-pack-sv-base/
language-pack-sw/
language-pack-sw-base/
language-pack-ta/
language-pack-ta-base/
language-pack-te/
language-pack-te-base/
language-pack-tet/
language-pack-tet-base/
language-pack-tg/
language-pack-tg-base/
language-pack-th/
language-pack-th-base/
language-pack-ti/
language-pack-ti-base/
language-pack-tk/
language-pack-tk-base/
language-pack-tl/
language-pack-tl-base/
language-pack-tlh/
language-pack-tlh-base/
language-pack-tr/
language-pack-tr-base/
language-pack-ts/
language-pack-ts-base/
language-pack-tt/
language-pack-tt-base/
language-pack-ug/
language-pack-ug-base/
language-pack-uk/
language-pack-uk-base/
language-pack-ur/
language-pack-ur-base/
language-pack-uz/
language-pack-uz-base/
language-pack-ve/
language-pack-ve-base/
language-pack-vi/
language-pack-vi-base/
language-pack-wa/
language-pack-wa-base/
language-pack-wo/
language-pack-wo-base/
language-pack-xh/
language-pack-xh-base/
language-pack-yi/
language-pack-yi-base/
language-pack-yo/
language-pack-yo-base/
language-pack-zu/
language-pack-zu-base/
language-pack-zza/
language-pack-zza-base/
language-support-af/
language-support-am/
language-support-ar/
language-support-as/
language-support-ast/
language-support-az/
language-support-be/
language-support-bg/
language-support-bn/
language-support-bo/
language-support-br/
language-support-bs/
language-support-ca/
language-support-cs/
language-support-cy/
language-support-da/
language-support-dz/
language-support-el/
language-support-eo/
language-support-eu/
language-support-fa/
language-support-fi/
language-support-fo/
language-support-fonts-am/
language-support-fonts-ar/
language-support-fonts-as/
language-support-fonts-bn/
language-support-fonts-bo/
language-support-fonts-dz/
language-support-fonts-fa/
language-support-fonts-gu/
language-support-fonts-he/
language-support-fonts-hi/
language-support-fonts-ii/
language-support-fonts-km/
language-support-fonts-kn/
language-support-fonts-lo/
language-support-fonts-ml/
language-support-fonts-mn/
language-support-fonts-mnc/
language-support-fonts-mr/
language-support-fonts-my/
language-support-fonts-ne/
language-support-fonts-or/
language-support-fonts-pa/
language-support-fonts-ta/
language-support-fonts-te/
language-support-fonts-th/
language-support-fonts-ur/
language-support-fonts-yi/
language-support-ga/
language-support-gd/
language-support-gl/
language-support-gu/
language-support-gv/
language-support-he/
language-support-hi/
language-support-hr/
language-support-hu/
language-support-hy/
language-support-ia/
language-support-id/
language-support-ii/
language-support-is/
language-support-it/
language-support-ka/
language-support-km/
language-support-kn/
language-support-ku/
language-support-lg/
language-support-li/
language-support-lo/
language-support-lt/
language-support-lv/
language-support-mg/
language-support-mi/
language-support-mk/
language-support-ml/
language-support-mn/
language-support-mnc/
language-support-mr/
language-support-ms/
language-support-my/
language-support-nb/
language-support-ne/
language-support-nl/
language-support-nn/
language-support-no/
language-support-nr/
language-support-nso/
language-support-oc/
language-support-or/
language-support-pa/
language-support-pl/
language-support-pt/
language-support-rm/
language-support-ro/
language-support-rw/
language-support-se/
language-support-si/
language-support-sk/
language-support-sl/
language-support-sq/
language-support-sr/
language-support-ss/
language-support-st/
language-support-sv/
language-support-sw/
language-support-ta/
language-support-te/
language-support-tg/
language-support-th/
language-support-ti/
language-support-tk/
language-support-tl/
language-support-tn/
language-support-tr/
language-support-translations-af/
language-support-translations-ar/
language-support-translations-as/
language-support-translations-be/
language-support-translations-bg/
language-support-translations-bn/
language-support-translations-br/
language-support-translations-bs/
language-support-translations-ca/
language-support-translations-cs/
language-support-translations-cy/
language-support-translations-da/
language-support-translations-dz/
language-support-translations-el/
language-support-translations-eo/
language-support-translations-eu/
language-support-translations-fa/
language-support-translations-fi/
language-support-translations-ga/
language-support-translations-gl/
language-support-translations-gu/
language-support-translations-he/
language-support-translations-hi/
language-support-translations-hr/
language-support-translations-hu/
language-support-translations-it/
language-support-translations-ka/
language-support-translations-km/
language-support-translations-kn/
language-support-translations-ku/
language-support-translations-lo/
language-support-translations-lt/
language-support-translations-lv/
language-support-translations-mk/
language-support-translations-ml/
language-support-translations-mr/
language-support-translations-nb/
language-support-translations-ne/
language-support-translations-nl/
language-support-translations-nn/
language-support-translations-no/
language-support-translations-nr/
language-support-translations-nso/
language-support-translations-oc/
language-support-translations-or/
language-support-translations-pa/
language-support-translations-pl/
language-support-translations-pt/
language-support-translations-ro/
language-support-translations-rw/
language-support-translations-sk/
language-support-translations-sl/
language-support-translations-sr/
language-support-translations-ss/
language-support-translations-st/
language-support-translations-sv/
language-support-translations-sw/
language-support-translations-ta/
language-support-translations-te/
language-support-translations-tg/
language-support-translations-th/
language-support-translations-ti/
language-support-translations-tn/
language-support-translations-tr/
language-support-translations-ts/
language-support-translations-uk/
language-support-translations-ur/
language-support-translations-uz/
language-support-translations-ve/
language-support-translations-vi/
language-support-translations-xh/
language-support-translations-za/
language-support-translations-zu/
language-support-ts/
language-support-ug/
language-support-uk/
language-support-ur/
language-support-uz/
language-support-ve/
language-support-vi/
language-support-wa/
language-support-wo/
language-support-writing-af/
language-support-writing-am/
language-support-writing-ar/
language-support-writing-bg/
language-support-writing-bn/
language-support-writing-br/
language-support-writing-ca/
language-support-writing-cs/
language-support-writing-cy/
language-support-writing-da/
language-support-writing-el/
language-support-writing-eo/
language-support-writing-eu/
language-support-writing-fa/
language-support-writing-fi/
language-support-writing-fo/
language-support-writing-ga/
language-support-writing-gd/
language-support-writing-gl/
language-support-writing-gu/
language-support-writing-gv/
language-support-writing-he/
language-support-writing-hi/
language-support-writing-hr/
language-support-writing-hu/
language-support-writing-hy/
language-support-writing-id/
language-support-writing-is/
language-support-writing-it/
language-support-writing-ku/
language-support-writing-lt/
language-support-writing-lv/
language-support-writing-ml/
language-support-writing-mr/
language-support-writing-nb/
language-support-writing-ne/
language-support-writing-nl/
language-support-writing-nn/
language-support-writing-no/
language-support-writing-nr/
language-support-writing-nso/
language-support-writing-or/
language-support-writing-pa/
language-support-writing-pl/
language-support-writing-pt/
language-support-writing-ro/
language-support-writing-se/
language-support-writing-sk/
language-support-writing-sl/
language-support-writing-ss/
language-support-writing-st/
language-support-writing-sv/
language-support-writing-sw/
language-support-writing-ta/
language-support-writing-te/
language-support-writing-tg/
language-support-writing-th/
language-support-writing-tl/
language-support-writing-tn/
language-support-writing-ts/
language-support-writing-uk/
language-support-writing-uz/
language-support-writing-ve/
language-support-writing-xh/
language-support-writing-zu/
language-support-xh/
language-support-yi/
language-support-yo/
language-support-za/
language-support-zu/
