#!/bin/bash

srcdir=$(readlink -f "${0%/*}")
destdir=$(readlink -f "$1")
tmpdir=$(mktemp -d)

cd $tmpdir
for src in "$srcdir"/DataTables*.zip; do
    unzip "$src"
    mv DataTables-*/* .
    rmdir DataTables-*/

    mv * "$destdir"/
    break
done

rmdir $tmpdir

