#!/bin/bash
    RCSID='$Id$'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"
    . shlib-import cliboot

    force=0

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Dereference of symlinks"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FILES"
    echo
    echo "Options: "
    echo "    -f, --force             error continue, exit 1 if any error"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -f|--force)
            force=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    err=0
    CP="cp --preserve --"

    for f in "$@"; do
        if [ -h "$f" ]; then

            tmp="$f.deref-$$-$RANDOM"
            if [ -d "$f" ]; then
                _log2 "Deref $f/"
                $CP -R "$f" "$tmp"
            else
                _log2 "Deref $f"
                $CP "$f" "$tmp"
            fi
            cp_err=$?
            if [ $cp_err != 0 ]; then
                err=1
            else
                _log2 "  remove"
                if rm -fR "$f"; then
                    _log2 "  rename"
                    if mv "$tmp" "$f"; then
                        _log2 "  done"
                    else
                        _log2 "  can't rename, leave the tmp file $tmp"
                    fi
                else
                    _log2 "  can't remove, leave the tmp file $tmp"
                fi
            fi
        fi

        if [ $err = 1 ] && [ $force != 1 ]; then
            break
        fi
    done

    return $err
}

boot "$@"
