#!/bin/bash
    . shlib-import cliboot

    shopt -s nullglob
    shopt -s dotglob

    RCSID='$Id: bash.sh 2255 2011-01-01 06:58:58Z lenik $'
    short_opts="Lhqv"
    long_opts="follow,help,quiet,verbose,version"

    symlinks=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Keep empty directories from ignored by Git"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -L, --follow            Follow symlinks"
    echo "    -H, --follow-args       Follow symlinks for arguments only"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -L|--follow)
            symlinks=follow;;
        -H|--follow-args)
            symlinks=follow-args;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ $# = 0 ]; then
        _log1 "Scan empty directories under current directory"
        scan .
    else
        for d in "$@"; do
            [ -d "$d" ] || die "Not a directory: $d"

            if [ -L "$d" ] && [ -z "$symlinks" ]; then
                _warn "Ignored symlink: $d"
                continue
            fi

            _log1 "Scan empty directories under $d"
            scan "$d"
        done
    fi
}

function scan() {
    local d="$1"

    child=("$d"/*)
    if [ ${#child} = 0 ]; then
        _log1 "  Found empty directory: $d"
        hold "$d"
    fi

    for subdir in "$d"/*/; do
        subdir="${subdir%/}"
        [ -L "$d" ] && [ "$symlinks" != 'follow' ] && continue

        _log3 "    Scan recursive into $subdir"
        scan "$subdir"
    done
}

boot "$@"
