.\"
.\"
.\" passwd.tc manpage
.\" Copyright (C) 2010 Xie Jilei (Lenik)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH PASSWD.TC 5
.SH NAME
passwd.tc \- Passwords used by mount.tc(1)
.SH DESCRIPTION
This file defines passwords for profiles used by fstab.tc and mount.tc.

.SH FORMAT

.B
PROFILE:PASSWORD (In plain text)

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Xie Jilei <xjl@99jsj.com>
.br
