#!/bin/bash

d=`readlink -f .`
rel="${d##*/uni/}"

vcslines=`grep Vcs- debian/control | wc -l`
lines=$((1 + vcslines))

lineconf -l$lines debian/control Homepage: \
    "Homepage: http://uni.bodz.net/$rel" \
    "Vcs-Git: git://git.bodz.net/uni.git" \
    "Vcs-Browser: http://git.bodz.net/uni/$rel"
