.TH [CIDEB] "1" "March 2020" "boDz" "User Commands"
.SH NAME
[cideb] \- cideb
.SH SYNOPSIS
.B cideb
[\fI\,OPTIONS\/\fR] [\fI\,--\/\fR] ...
.SH OPTIONS
.TP
\fB\-b\fR, \fB\-\-batch\-mode\fR
Build only, don't upgrade the system.
.HP
\fB\-D\fR, \fB\-\-distribution\fR=\fI\,DIST\/\fR Set distribution name.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Be more quiet.
.IP
Repeat this option to reduce the verbosity of information to output.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.IP
Repeat this option to expand the verbosity of information to output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help page.
.IP
Display a brief usage for this command, and exit.
.TP
\fB\-\-version\fR
Print the version information.
.IP
Print the program title, a short description, and the version string
at the very beginning, and exit.
.SH AUTHOR
Written by Lenik, Version 1.13.4, Last updated at 2020\-03\-12
