#!/bin/bash

for path in "$@"; do
    if [ "${path%/%gconf.xml}" = "$path" ]; then
        f="$path/%gconf.xml"
    else
        f="$path"
    fi
    userf="$HOME/.gconf/$f"
    if [ ! -f "$userf" ]; then
        echo "File $userf isn't existed. "
    else
        echo "Copy $userf"
        cp "$userf" "$f"
    fi
done
