#!/bin/bash

# Remove the original refs backed up git-filter-branch.
git for-each-ref --format="%(refname)" refs/original/ \
    | xargs -rn1 git update-ref -d

git reflog expire --expire=now --all

git gc --prune=now
