.TH [COLLECT-COPY] "1" "April 2016" "boDz" "User Commands"
.SH NAME
[collect-copy] \- collect-copy
.SH SYNOPSIS
.B collect-copy
[\fI\,OPTIONS\/\fR] [\fI\,--\/\fR] ...
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-root\fR=\fI\,DIR\/\fR
Root dir of coll\-repo, default \fI\,/var/lib/coll\/\fP.
.TP
\fB\-c\fR, \fB\-\-category\fR=\fI\,NAME\/\fR
Specify category name.
.TP
\fB\-n\fR, \fB\-\-norm\fR=\fI\,NORM\-TYPE\/\fR
How to normalize path.
.TP
\fB\-x\fR, \fB\-\-norm\-exec\fR=\fI\,CMD\/\fR
Using 'exec' norm type, and specify the cmd.
.TP
\fB\-f\fR, \fB\-\-find\fR=\fI\,PATTERN\/\fR
Get file list by find PATTERN from curdir.
.TP
\fB\-s\fR, \fB\-\-stdin\fR
Read file list from stdin (when stream from find, it should be find \fB\-printf\fR '%p\en\ec').
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Be more quiet.
.IP
Repeat this option to reduce the verbosity of information to output.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.IP
Repeat this option to expand the verbosity of information to output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help page.
.IP
Display a brief usage for this command, and exit.
.TP
\fB\-\-version\fR
Print the version information.
.IP
Print the program title, a short description, and the version string
at the very beginning, and exit.
.PP
Normalization Types:
(Example path: ./any/libsepol\-2.0.40/debian/postinst)
.TP
c (default)
__any_libsepol\-2.0.40_debian_postinst
.TP
dash (or \-)
any\-libsepol\-2.0.40\-debian\-postinst
.TP
dash\-any\-debian
libsepol\-2.0.40\-postinst
.SH AUTHOR
Written by Lenik, Version 0.10.0, Last updated at 2016\-04\-07
