.TH [HTMLDOC-MAN] "1" "April 2016" "boDz" "User Commands"
.SH NAME
[htmldoc-man] \- htmldoc-man
.SH SYNOPSIS
.B htmldoc-man
[\fI\,OPTION\/\fR] [\fI\,--\/\fR] [\fI\,nnn\/\fR] \fI\,PACKAGE-SPEC KEYWORDS\/\fR...
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-packages\fR
List packages which contains html docs.
.TP
\fB\-I\fR, \fB\-\-include\fR=\fI\,DIR\/\fR
Add dir to search path.
.TP
\fB\-d\fR, \fB\-\-maxdepth\fR=\fI\,DEPTH\/\fR
Max recursion depth to search into.
.TP
\fB\-a\fR, \fB\-\-all\fR
Search all keywords with the prefix.
.TP
\fB\-s\fR, \fB\-\-strict\fR
Search explicit keywords.
.TP
\fB\-i\fR, \fB\-\-ignore\-case\fR
Ignore case.
.TP
\fB\-l\fR, \fB\-\-list\fR
Only list the candidates, don't open.
.TP
\fB\-x\fR, \fB\-\-exec\fR=\fI\,COMMAND\/\fR
Open with specified command.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Repeat to get less info.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Repeat to get more info.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help page.
.TP
\fB\-\-version\fR
Print the version info.
.SH AUTHOR
Written by Lenik, Version 0.10.0, Last updated at 2016\-04\-07
