#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="b:hqv"
    long_opts="byte:,help,quiet,verbose,version"

    byte=0
    size=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Fill a file with zero"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FILE SIZE[kmgKMG]"
    echo
    echo "Options: "
    echo "    -b, --byte=NUM          The byte value used to fill the file"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -b|--byte)
            byte=$2;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ $# -lt 2 ]; then
        echo "File or size isn't specified. "
        exit 1
    fi

    file="$1"
    size="$2"
    if [ -f "$file" ]; then
        echo "File $file is already existed. "
        exit 1
    fi

    case "$size" in
        *k) size=${size%k}; block=1000;;
        *K) size=${size%K}; block=1024;;
        *m) size=${size%m}; block=1000000;;
        *M) size=${size%M}; block=1048576;;
        *g) size=${size%g}; block=1000000000;;
        *G) size=${size%G}; block=1073741824;;
        *[0-9]) block=1;;
        *)
            echo "Invalid size: $size"
            exit 1;;
    esac

    dd bs=$block count=$size if=/dev/zero of="$file"
}

boot "$@"
