FROM leicent:latest
MAINTAINER Lenik <lenik@bodz.net>
LABEL \
    description = "Lenik's CentOS base OS for app cluster" \
    version = "1.0"

#RUN yum install -y net-tools
#RUN yum install -y rabbitmq-server

CMD ["/bin/bash", "-i"]
