#!/bin/bash

_histfile=$HOME/.bash_history

if [ -n "$1" ]; then
    _histfile="$1"
fi

if [ ! -f "$_histfile" ]; then
    echo "$_histfile isn't exsited. "
    exit 1
fi

if [ ! -w "$_histfile" ]; then
    echo "$_histfile is read-only. "
    exit 1
fi

tmpout=`tempfile`

t=

if ! paste -s -d ':\n' | grep -v '^#'; then
    echo "Some history don't have timestamp!"
    exit 1
fi

paste -s -d ':\n' "$_histfile" \
    | sort -b2- -n \
    |

#mv -f "$_histfile" "$_histfile~"
#mv $tmpout "$_histfile"
