# vim: set filetype=sh :

#alias     add='git add'
alias       br='git branch'
alias      cdf='git clean -df'
alias       ci='git commit -v'
#alias ciamend='git commit -a --amend'
#alias   clone='git clone'
alias       co='git checkout'
alias       di='git diff'
alias       gd='git delta'
#alias      fe='git fetch'
alias      gmt='git mergetool --tool=meld'
#alias      gr='git grep'
alias      log='git log --color=always'
#alias      mg='git merge'
alias     pull='git pull'
alias     pure='git pull --rebase'
alias     push='git push'
alias      grb='git rebase'
alias      grv='git remote -v'
#alias   reset='git reset'
alias      grh='git reset --hard'
#alias  revert='git revert'
alias    griom='git rebase -i origin/master'
#alias     sho='git show'       # See vcscmd::show
alias       st='git status'
alias    stash='git stash'
alias      tag='git tag'
alias       gg='gitg'
