# vim: set filetype=sh :

alias      gbr='git branch'
alias      gci='git commit'
alias   gclone='git clone'
alias      gco='git checkout'
alias      gdi='git diff'
alias      gmt='git mergetool'
alias     glog='git log'
alias    gpull='git pull'
alias     pure='git pull --rebase'
alias    gpush='git push'
alias   gstash='git stash'
alias      gst='git status'
alias     gtag='git tag'

alias     cira='git commit --amend --reset-author -C HEAD'
alias       gd='git delta'
alias      gmt='git mergetool --tool=meld'
alias     pure='git pull --rebase'
alias      grh='git reset --hard'
alias    griom='git rebase -i origin/master'
alias      grr='git remote-ref origin'
alias       gg='gitg'

