#!/bin/bash

for f in "$@"; do
    if ! p=`which $f`; then
        echo "Not found $f, skipped"
        continue
    fi

    file "$p"; echo
    # stat "$p"; echo

    if textp "$p"; then
        lines=`wc "$p" | awk '{ print $1 }'`
        if [ $lines -le 20 ]; then
            echo "Contents of $p"
            echo "-------------------------"
            cat $p | sed 's/^/> /'
            echo
        else
            echo "Header of $p"
            echo "-------------------------"
            head -10 $p | sed 's/^/> /'
            echo

            echo "Footer of $p"
            echo "-------------------------"
            tail -10 $p | sed 's/^/> /'
            echo
        fi
    fi
done
