#!/bin/bash
    : ${RCSID:=$Id: - @VERSION@ @DATE@ @TIME@ - $}
    : ${PROGRAM_TITLE:="Merge Orig"}
    : ${PROGRAM_SYNTAX:="[OPTIONS] [--] orig-srcdir"}

    . shlib-import cliboot
    option -q --quiet       "Repeat to get less info"
    option -v --verbose     "Repeat to get more info"
    option -h --help        "Show this help page"
    option    --version     "Print the version info"

    shopt -s nullglob

function setopt() {
    case "$1" in
        -h|--help)
            help $1; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ ! -d "$1/assembler" ]; then
        echo "orig-srcdir isn't specified or not exists."
        echo
        echo "You may get orig copy by:"
        echo "    git clone git://git.bues.ch/b43-tools.git"
        exit 1
    fi

    orig="${1%/}"

    _log2 cp -v -a "$orig" .
    cp -uv -a "$orig"/* .
}

boot "$@"
