#!/bin/bash

if [ $# -lt 3 ]; then
    echo "backup <srcfile> <bakdir> <intv (minutes)>"
    exit 1
fi


    srctime=`stat -c%Z $src`
    baktime=0
    if [ -e $bak ]; then
        baktime=`stat -c%Z $bak`
    fi