.TH URLJOIN "1" "July 2017" "boDz" "User Commands"
.SH NAME
urljoin \- urljoin
.SH SYNOPSIS
.B urljoin
[\fI\,OPTIONS\/\fR] [\fI\,--\/\fR] \fI\,<ctx-url> \/\fR[\fI\,<url-spec>\/\fR...]
.SH OPTIONS
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Be more quiet.
.IP
Repeat this option to reduce the verbosity of information to output.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.IP
Repeat this option to expand the verbosity of information to output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help page.
.IP
Display a brief usage for this command, and exit.
.TP
\fB\-\-version\fR
Print the version information.
.IP
Print the program title, a short description, and the version string
at the very beginning, and exit.
.SH AUTHOR
Written by Lenik, Version 0.4.3, Last updated at 2017\-07\-28
