.TH [WGETC] "1" "March 2021" "boDz" "User Commands"
.SH NAME
[wgetc] \- wgetc
.SH SYNOPSIS
.B wgetc
[\fI\,OPTIONS\/\fR] [\fI\,--\/\fR] \fI\,URL(s)\/\fR
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-mode\fR=\fI\,MODE\/\fR
chmod to downloaded file.
.TP
\fB\-f\fR, \fB\-\-force\fR
Invalidate the correspond cache.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Be more quiet.
.IP
Repeat this option to reduce the verbosity of information to output.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be more verbose.
.IP
Repeat this option to expand the verbosity of information to output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help page.
.IP
Display a brief usage for this command, and exit.
.TP
\fB\-\-version\fR
Print the version information.
.IP
Print the program title, a short description, and the version string
at the very beginning, and exit.
.SH AUTHOR
Written by Lenik, Version 1.0.5, Last updated at 2021\-03\-31
