.TH [WGET-GREP-URL] "1" "April 2023" "boDz" "User Commands"
.SH NAME
[wget-grep-url] \- wget-grep-url
.SH SYNOPSIS
.B wget-grep-url
[\fI\,OPTIONS\/\fR] [\fI\,--\/\fR] \fI\,PATTERN START-URL\/\fR
.SH OPTIONS
.TP
\fB\-E\fR, \fB\-\-extended\-regexp\fR
Using extended regexp (ERE, default).
.TP
\fB\-P\fR, \fB\-\-perl\-regexp\fR
Using perl regexp (PRE).
.TP
\fB\-m\fR, \fB\-\-max\-count\fR=\fI\,NUM\/\fR
max urls to get.
.TP
\fB\-s\fR, \fB\-\-strict\fR
Strict match.
.TP
\fB\-j\fR, \fB\-\-join\fR
Join the href with the starting urls.
.TP
\fB\-J\fR, \fB\-\-no\-join\fR
Don't join href with urls.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Repeat to get less info.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Repeat to get more info.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help page.
.TP
\fB\-\-version\fR
Print the version info.
.SH AUTHOR
Written by Lenik, Version 1.0.6, Last updated at 2023\-04\-26
