#!/bin/bash

for url in "$@"; do
    ext="${url##*.}"
    if [ "$ext" = "url" ] && [ -f "$url" ]; then
        while read line; do
            url="${line#URL=}"
            gnome-open "$url"
            break
        done < <(grep '^URL=' "$url")
    elif [ "${url/:\/\/}" != "$url" ]; then
        gnome-open "$url"
    else
        echo "Bad url format: $url"
    fi
done
