#!/bin/bash

# bash for $RANDOM

if [ $# -lt 2 ]; then
    echo "$0 FILE COMMAND [ARGS...]"
    exit 1
fi

file="$1"
shift

# keep file extension, maybe some program need it.
buff="/tmp/sedit-$file.$$"

"$@" <"$file" >"$buff"
err=$?

if ! cmp -s "$file" "$buff"; then
    # contents changed

    # TODO: option to keep the last-mod-time not changed.
    # touch -r "$file" "$buff"

    chmod --reference "$file" "$buff"

    # overwrite self
    mv -f "$buff" "$file"
fi

rm -f "$buff"

exit $err

#!/bin/bash
    RCSID='$Id: .sh 1023 2009-04-29 23:50:10Z Shecti $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"
    . $LAM_KALA/lib/sh/cliboot

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Bash_simple_cli_program_template"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    dump "$@"
    echo Done.
}

boot "$@"
