.\"
.\"
.\" sedit.man - sedit manpage
.\" Copyright (C) 2010 Xie Jilei (Lenik)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH SEDIT 1
.SH NAME
sedit \- In-place edit in streaming manner
.SH SYNOPSIS
.B sedit
[OPTIONS] FILE COMMAND [ARGS]
.SH DESCRIPTION
sedit pipe the FILE contents into COMMAND, which in turns processes the stdin, its output will be captured by sedit and buffered. After the COMMAND finished, the buffered contents replace the original FILE.

.SH EXAMPLES

.PP
Insert something before the file header:
.B
sedit FILE cat header -

.PP
Insert something before line NN:
.B
sedit FILE sh -c "head -NN; echo something; cat"

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Xie Jilei <xjl@99jsj.com>
.br
