#!/bin/bash

if [ "$1" = "-f" ]; then
	khfile="$2"
	shift 2
else
	khfile=`ssh-globalknownhosts`
fi

if [ $# -lt 1 ]; then
	echo "$0 [-f KnownHostsFile] HostName..."
	exit 1
fi

echo -n >>$khfile

tmp=`tempfile`
ssh-keyscan -t rsa,dsa "$@" | sort -u - $khfile >$tmp
cat $tmp >$khfile
rm -f $tmp
