#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="p:hqv"
    long_opts="port,help,quiet,verbose,version"

    JETTY_PLUGIN=org.mortbay.jetty:maven-jetty-plugin

    port=3108

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Start jetty by maven-plugins"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION]"
    echo
    echo "Options: "
    echo "    -p, --port=PORT         Specify http port to listen"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -p|--port)
            port=$2;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    mvn -Djetty.port=$port $JETTY_PLUGIN:run
}

boot "$@"
