#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id$'
    short_opts="p:dP:hqv"
    long_opts="port,debug,debug-port,help,quiet,verbose,version"

    JETTY_PLUGIN=org.mortbay.jetty:maven-jetty-plugin

    mvnopts=()
    nmvnopt=0

    port=3108
    debug=0
    debug_port=3104

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Start jetty by maven-plugins"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] <project-dir>"
    echo
    echo "Options: "
    echo "    -p, --port=PORT         HTTP port, default 3108"
    echo "    -d, --debug             Enable remote debugging"
    echo "    -P, --debug-port=PORT   Debug port, default 3104"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -p|--port)
            port=$2;;
        -d|--debug)
            debug=1;;
        -P|--debug-port)
            debug_port=$2;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ -n "$1" ]; then
        cd "$1" || exit
    fi

    if [ "$debug" = 1 ]; then
        agent=1
        if [ "$agent" = 1 ]; then
            mvnopts[nmvnopt++]=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$debug_port
        else
            # Java<=1.5
            mvnopts[nmvnopt++]=-Xdebug
            mvnopts[nmvnopt++]=-Xnoagent
            mvnopts[nmvnopt++]=-Xrunjdwp:transport=dt_socket,address=$debug_port,servery=y,suspend=n
        fi
        # mvnopts[nmvnopt++]=-Djava.compiler=NONE
    fi

    export MAVEN_OPTS="${mvnopts[*]}"

    mvn -Djetty.port=$port $JETTY_PLUGIN:run
}

boot "$@"
