#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id$'
    short_opts="CD:EGorpS:Tl:O:dhqv"
    long_opts="no-cascade,direction,no-external,no-groupid,omitted,no-optional,pom,hide-scopes,no-transitive,label,output,display,help,quiet,verbose,version"

    GRAPH_PLUGIN=org.fusesource.mvnplugins:maven-graph-plugin
    DEFAULT_OUT=target/project-graph.png

    opts=()
    nopt=0

    display=
    outfile=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Maven project graph"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -C, --no-cascade        Don't cascade test-scope and optionals"
    echo "    -D, --direction=DIR     One of TB LR BT RL"
    echo "    -E, --no-external       Hide external dependencies"
    echo "    -G, --no-groupid        Hide group id"
    echo "    -o, --omitted           Show omitted dependencies"
    echo "    -r, --no-optional       Hide optional dependencies"
    echo "    -p, --pom               Show pom dependencies"
    echo "    -S, --hide-scope=SCOPES Hide specific scopes, separate scope by comma"
    echo "    -T, --no-transitive     Hide non-explicitly defined dependencies"
    echo "    -l, --label=LABEL       Set the graph label"
    echo "    -O, --output=FILE       Output to the file, in extension format"
    echo "    -d, --display           Open the result graph file"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -C|--no-cascade)
            opts[nopt++]="-Dcascade=false";;
        -D|--direction)
            # one of: TB LR BT RL
            opts[nopt++]="-Dgraph.direction=$2";;
        -E|--no-external)
            opts[nopt++]="-Dhide-external=true";;
        -G|--no-groupid)
            opts[nopt++]="-Dhide-group-id=true";;
        -o|--omitted)
            opts[nopt++]="-Dhide-omitted=false";;
        -r|--no-optional)
            opts[nopt++]="-Dhide-optional=true";;
        -p|--pom)
            opts[nopt++]="-Dhide-poms=false";;
        -S|--hide-scopes)
            opts[nopt++]="-Dhide-scope=$2";;
        -T|--no-transitive)
            opts[nopt++]="-Dhide-transitive=true";;
        -l|--label)
            opts[nopt++]="-Dgraph.label=$2";;
        -O|--output)
            opts[nopt++]="-Dgraph.target=$2"
            outfile="$2"
            ;;
        -d|--display)
            display=display;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    MVN=mvn
    if [ $LOGLEVEL -le 1 ]; then
        MVN="mvn -q"
    else
        MVN="mvn -e"
    fi

    _log2 $MVN $GRAPH_PLUGIN:project "${opts[@]}"
    $MVN $GRAPH_PLUGIN:project "${opts[@]}"

    if [ -z "$outfile" ]; then
        display $DEFAULT_OUT
    else
        if [ -n "$display" ]; then
            $display "$outfile"
        fi
    fi
}

boot "$@"
