#!/bin/bash

#GROUP_ID="$1"
#PARENT_ID="$2"
#PARENT_VERSION="$3"
PARENT_ID="${PWD##*/}"

while read g; do
    g="${g##*<groupId>}"
    g="${g%%</groupId>*}"
    GROUP_ID="$g"
done < <(grep -C4 "$PARENT_ID" pom.xml | grep "<groupId>")

if _ver=`grep -A3 "$PARENT_ID" pom.xml | grep "<version>"`; then
	_ver="${_ver##*<version>}"
	_ver="${_ver%%</version>*}"
	PARENT_VERSION="$_ver"
else
	echo "Can't find parent version from pom.xml"
fi

echo "Parent: $GROUP_ID:$PARENT_ID:$PARENT_VERSION"

if [ $# -lt 2 ]; then
    echo "newmod ID NAME [PACKAGE]"
    exit 1
fi

ID="$1"
NAME="$2"

GROUP_SUFFIX="${GROUP_ID##*.}"
ID_PREFIX="${ID%%-*}"
if [ "$GROUP_SUFFIX" = "$ID_PREFIX" ]; then
    PACKAGE="$GROUP_ID.${ID#*-}"
else
    PACKAGE="$GROUP_ID.$ID"
fi
PACKAGE="${PACKAGE//-/.}"
if [ -n "$3" ]; then PACKAGE="$3"; fi

VERSION=0.0.1-SNAPSHOT
echo "Module: $GROUP_ID:$ID:$VERSION"
echo "Package: $PACKAGE"

mkdir $ID
cat <<EOM >$ID/pom.xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>$GROUP_ID</groupId>
        <artifactId>$PARENT_ID</artifactId>
        <version>$PARENT_VERSION</version>
    </parent>
    <artifactId>$ID</artifactId>
    <version>$VERSION</version>
    <dependencies />
    <name>$NAME</name>
</project>
EOM

PDIR="${PACKAGE//./\/}"
mkdir -p $ID/src/main/java/$PDIR
mkdir -p $ID/src/main/resources/$PDIR
mkdir -p $ID/src/test/java/$PDIR
mkdir -p $ID/src/test/resources/$PDIR

cd $ID
mvn eclipse:m2eclipse
cd ..
svn add -N $ID $ID/pom.xml
svn add $ID/src

IGNORE_FILE=/tmp/svnignore-$RANDOM.tmp
cat <<EOM >$IGNORE_FILE
.classpath
.project
.settings
target
EOM

svn ps svn:ignore -F $IGNORE_FILE $ID
rm -f $IGNORE_FILE
