#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Show help page of a Maven plugin"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] PLUGIN [NAME]"
    echo
    echo "Options: "
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    if [ $# -lt 1 ]; then
        help
        exit 1
    fi

    plugin="$1"
    shift

    if [ -n "$1" ]; then
        opt_goal=-Dgoal=$1
    else
        opt_goal=
    fi

    if [ $LOGLEVEL -gt 0 ]; then
        detail=true
    else
        detail=false
    fi

    mvn -q -Doutput=/dev/stdout \
           -Ddetail=$detail \
           -Dplugin=$plugin \
           $opt_goal \
           help:describe
}

boot "$@"
