#!/bin/bash

e_fx=0
e_color=31

case "$1" in
    -e)
        e_color="$2"
        shift 2
        ;;
    -E)
        e_fx="$2"
        shift 2
        ;;
esac

stdbuf -oL -eL "$@" 2> >( sed -u -e "s/^/[${e_fx};${e_color}m/" -e 's/$/[0m/' )

