#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="o:hqv"
    long_opts="output:,help,quiet,verbose,version"

    out=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Convert Raw image to VirtualBox VDI image"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] file.img"
    echo
    echo "Options: "
    echo "    -o, --output=vdifile    Output to filename different than file.vdi"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -o|--output)
            out="$2";;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    img="$1"
    if [ -z "$img" ]; then
        echo ".img file must be specified. "
        exit 1
    fi

    if [ -n "$2" ]; then
        out="$2"
    elif [ -z "$out" ]; then
        out="${img%.img}"
        out="${out%.IMG}"
        out="$out.vdi"
    fi

    VBoxManage internalcommands convertfromraw "$img" "$out" --format vdi
}

boot "$@"
