.\"
.\"
.\" img2vdi.man - img2vdi manpage
.\" Copyright (C) 2010 Lenik (谢继雷)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH IMG2VDI 1
.SH NAME
img2vdi \- Convert raw image file to Virtual Box .vdi disk image
.SH SYNOPSIS
.B img2vdi
[-o <vdi-file>]
.SH DESCRIPTION
Convert raw image file to Virtual Box .vdi disk image

.SH EXAMPLES

.B
img2vdi a.img
.PP
Convert a.img to a.vdi.

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Lenik <lenik at bodz.net>
.br
