#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="rfhqv"
    long_opts="register,force,help,quiet,verbose,version"

    force=
    register=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Create vmdk wrapper for raw device"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] raw-device .vmdk-file"
    echo
    echo "Options: "
    echo "    -r, --register          Register with media manager"
    echo "    -f, --force             Overwrite existing .vmdk file"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -r|--register)
            register=1;;
        -f|--force)
            force=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ $# != 2 ]; then
        help
        exit 1
    fi

    rawdev="$1"
    vmdk="$2"

    if [ ! -b "$rawdev" ]; then
        echo "Not a block device: $rawdev"
        exit 1
    fi

    if [ -e "$vmdk" ] && [ "$force" != 1 ]; then
        echo "File $vmdk is already existed. "
        exit 1
    fi

    _log1 "createrawvmdk: $vmdk -> $rawdev"

    opt_register=
    if [ "$register" = 1 ]; then
        opt_register=-register
    fi

    VBoxManage internalcommands createrawvmdk \
        -filename "$vmdk" -rawdisk "$rawdev" $opt_register
}

boot "$@"
