#!/bin/sh

# 1, do vercomp before commit
# 2, do update after commit on dir

if [ -z "$SVN" ]; then
    SVN=svn
fi

if [ $# = 0 ]; then
    svn
    exit
fi

cmd="$1"
cmd_opts_0=
shift

case "$cmd" in
    commit|ci)
        av=
        for d in . .. ../..; do
            if [ -f "$d/VERSION.av" ]; then
                av="$d/VERSION.av"
                break
            fi
        done
        if [ -n "$av" ]; then
            vercomp -i commit "$av" >/dev/null

            # do autover only if on top of srcdir.
            if [ -f configure.ac ]; then
                if AUTOVER=`which autover`; then
                    $AUTOVER
                fi
            fi
        fi
        ;;
    unadd)
        cmd=revert
        cmd_opts_0="--depth infinity"
        ;;
esac

$SVN $cmd $cmd_opts_0 "$@"
