#!/bin/sh

# 1, do vercomp before commit
# 2, do update after commit on dir

if [ -z "$SVN" ]; then
    SVN=svn
fi

if [ $# = 0 ]; then
    svn
    exit
fi

case "$1" in
    commit|ci)
        av=
        for d in . .. ../..; do
            if [ -f "$d/VERSION.av" ]; then
                av="$d/VERSION.av"
                break
            fi
        done
        if [ -n "$av" ]; then
            if svn st "$av" | grep -q '^M'; then
                vercomp -i commit "$av" >/dev/null

                # do autover only if on top of srcdir.
                if [ -f configure.ac ]; then
                    if AUTOVER=`which autover`; then
                        $AUTOVER
                    fi
                fi
            fi
        fi
        ;;

    unadd)
        shift
        set revert --depth infinity "$@"
        ;;
esac

$SVN "$@"
