#!/bin/bash

trueval='*'

if [ $# = 0 ]; then
    # If no argument was specified, recurse into current dir.
    find -name .svn -prune \
        -o -type f -exec $0 {} \;
    exit $?
fi

errcount=0

for f in "$@"; do

    if [ -d "$f" ]; then
        # recurse into directories.
        find "$f" -name .svn -prune \
            -o -type f -exec $0 {} \;
        exit $?
    fi

    # if f isn't versioned, print error message and exit 1
    # if f doesn't set the property, just return empty string.
    if oldval=`svn pg svn:executable "$f" 2>/dev/null`; then

        newval=
        if [ -x "$f" ]; then newval="$trueval"; fi

        if [ "$oldval" != "$newval" ]; then

            if [ -z "$newval" ]; then
                echo "$f: Clear executable"
                svn pd -q svn:executable "$f"
            else
                echo "$f: Set executable"
                svn ps -q svn:executable "$newval" "$f"
            fi

        fi # diff

    else
        ((errcount++))
    fi # versioned

done

exit $errcount
