#!/usr/bin/env perl

use strict;

my $count = 0;

my %used;

while (<>) {
    while (/\$(Id|Revision|Date|Author)\b(|(: .*?))\$/g) {
        $used{$1} = 1;
    }
}

my @used = keys %used;
sort @used;

print join(' ', @used);
exit (scalar(@used) ? 0 : 1);
