#!/bin/bash
    RCSID='$Id: bash.sh 1432 2010-08-25 10:23:46Z lenik $'
    short_opts="dhqv"
    long_opts="dryrun,help,quiet,verbose,version"
    . shlib import cliboot

    svnopts=
    dryrun=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Bash_simple_cli_program_template"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FROM-PATTERN TO-PATTERN FILES"
    echo
    echo "Options: "
    echo "    -d, --dryrun            only see what will be renamed"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -d|--dryrun)
            dryrun=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    if [ $LOGLEVEL -le 1 ]; then
        svnopts="-q"
    fi

    if [ $# -lt 3 ]; then
        help
        exit 1
    fi

    from="$1"
    to="$2"
    shift 2

    for f in "$@"; do
        dir="${f%/*}"
        base="${f##*/}"
        if [ "$dir" = "$f" ]; then
            g="${f/$from/$to}"
        else
            g="$dir/${base/$from/$to}"
        fi

        _log1 "Rename $f to $g"
        if [ "$dryrun" = 1 ]; then continue; fi

        svn mv $svnopts "$f" "$g"
    done
}

boot "$@"
