#!/bin/bash
    RCSID='$Id: bash.sh 1432 2010-08-25 10:23:46Z lenik $'
    short_opts="uhqv"
    long_opts="unversioned,help,quiet,verbose,version"
    . shlib-import cliboot

    LOGLEVEL=0
    unversioned=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Check if the working directory is full commited"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FILES"
    echo
    echo "Options: "
    echo "    -u, --unversioned       include unversioned files"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -u|--unversioned)
            unversioned=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    ignore_mode=X

    if [ "$unversioned" != 1 ]; then
        ignore_mode="$ignore_mode?"
    fi

    ignore_pattern="^[$ignore_mode]"

    if [ $# = 0 ]; then
        set .
    fi

    for d in "$@"; do

        _log2 "check dirty of $d"
        lines=`svn st --ignore-externals "$d" | grep -v "$ignore_pattern" | wc -l`
        if [ $lines != 0 ]; then
            _log1 dirty
            exit 1
        fi

    done

    _log1 clean
    exit 0
}

boot "$@"
