#!/bin/bash
    RCSID='$Id: bash.sh 1432 2010-08-25 10:23:46Z lenik $'
    short_opts="sakdhqv"
    long_opts="set,add,kill,diff,help,quiet,verbose,version"
    . /usr/lib/bash/cliboot

    mode=set
    diff=0

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Modify SVN multi-line property"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    svnpsl [OPTION] [--] PROPNAME PROPVAL... ; FILES"
    echo
    echo "Options: "
    echo "    -s, --set               set values (default)"
    echo "    -a, --add               add values"
    echo "    -k, --kill              delete values"
    echo "    -d, --diff              show diff of changes"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -s|--set)
            mode=set;;
        -a|--add)
            mode=add;;
        -k|--kill)
            mode=delete;;
        -d|--diff)
            diff=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ -z "$1" ]; then
        echo "Property name isn't specified. "
        exit 1
    fi

    name="$1"
    shift

    tmp_prefix=/tmp/svnprop-$$-$RANDOM
    tmp_vals=$tmp_prefix.vals
    tmp_orig=$tmp_prefix.orig

    term=0
    _log2 "Create vals tmp file"
        echo -n >$tmp_vals
        for v in "$@"; do
            shift
            if [ "$v" = ';' ]; then
                term=1
                break
            fi
            echo "$v" >>$tmp_vals
        done

    if [ $term != 1 ]; then
        echo "Property values list isn't ended by ';'. "
        exit 1
    fi

    for f in "$@"; do
        _log1 "Process file $f"

        case $mode in
        set)
            ;;

        add)
            svn pg "$name" "$f" >$tmp_orig
            cat $tmp_vals >>$tmp_orig
            sort -u $tmp_orig >$tmp_vals
            ;;

        delete)
            svn pg "$name" "$f" | grep -vFf $tmp_vals >$tmp_orig
            mv -f $tmp_orig $tmp_vals
            ;;
        esac

        # remove empty lines
        cp $tmp_vals $tmp_orig
        grep -v '^$' $tmp_orig >$tmp_vals

        # echo '--- vals ---'; cat $tmp_vals; echo '------------'

        if [ "$diff" = 1 ]; then
            svn pg "$name" "$f" | grep -v '^$' >$tmp_orig
            if diff -u $tmp_orig $tmp_vals; then
                _log2 "    No changes, skipped"
                continue
            fi
        fi

        if ! svn ps -F $tmp_vals "$name" "$f"; then
            echo "    Error set property $name on $f" >&2
            exit 1
        fi
    done

    rm -f $tmp_orig
    rm -f $tmp_vals
}

boot "$@"
