.TH NEWMAN 1
.SH NAME
newman \- Create simple stupid man page
.SH SYNOPSIS
.B newman
NAME SECTION SHORT-DESCRIPTION
.SH DESCRIPTION
Create simple stupid man page.

.SH EXAMPLES

.B
newman myprogram 1 "my program does stupid things"
.PP
Create a simple man page for myprogram, the file will be myprogram.1.

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Lenik <lenik at bodz.net>
.br
