#!/bin/bash
    RCSID='$Id: .sh 1023 2009-04-29 23:50:10Z Shecti $'
    short_opts="a:A:e:hqv"
    long_opts="help,quiet,verbose,version"
    . shlib import cliboot

    author_name="$DEBFULLNAME"
    author_alias="$USERNAME"
    if [ -z "$author_name" ]; then
        author_name="$author_alias"
        author_alias=
    elif [ "${author_name/\(}" != "$author_name" ]; then
        n1="${author_name%\(*}"
        n1="${n1% }"
        n2="${author_name#*\(}"
        n2="${n2# }"
        n2="${n2%\)}"
        n2="${n2% }"
        author_name="$n1"
        author_alias="$n2"
    fi

    email=$EMAIL
    if [ -z "$email" ]; then
        email="$DEBEMAIL"
    fi

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] (Simple stupid) Man page generator"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] NAME SECTION SHORT-DESC"
    echo
    echo "Options: "
    echo "    -a, --author=AUTHOR     author full name"
    echo "    -A, --alias=ALIAS       author alias"
    echo "    -e, --email=EMAIL       specify the bug-report email"
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -a|--author)
            author_name="$2";;
        -A|--alias)
            author_alias="$2";;
        -e|--email)
            email="$2";;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    if [ $# != 3 ]; then
        help
        exit 1
    fi

    name="$1"
    uname=`uc -e $name`
    section="$2"
    shortdesc="$3"

    manfile="$name.$section"

    year=`date +%Y`

    if [ -n "$author_alias" ]; then
        author_alias=" ($author_alias)"
    fi

    if [ -n "$email" ]; then
        email=" <${email/@/ at }>"
    fi

    cat <<EOT >$manfile
.\"
.\"
.\" $name.man - $name manpage
.\" Copyright (C) $year $author_name$author_alias
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH $uname $section
.SH NAME
$name \- $shortdesc
.SH SYNOPSIS
.B $name
ARGUMENTS
.SH DESCRIPTION
$shortdesc

.SH EXAMPLES

.B
$name example-arguments
.PP
example-description

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
$author_name$email
.br
EOT
}

boot "$@"
