#!/bin/bash

# Find the true mount program in PATH
mount=`whichother mount`

$mount $*
last=$?
if [ $? -eq 0 ]; then
    if [ $# -gt 0 ]; then
        shift $(($#-1))
        if [ ${1:0:1} != '-' ]; then
            # readlink -f $1
            # echo Last mounted to: $1
            if [ -r $1/.VEX/auto.mount.sh ]; then
                . $1/.VEX/auto.mount.sh
            fi
        fi
    fi
fi

exit $last
