/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.40 from the
 * contents of libchm.xs. Do not edit this file, edit libchm.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "libchm.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#include "chm_lib.h"
#include "const-c.inc"
/* #include <xsutil.h> */

/*
typedef unsigned int        chm_ulong_t;
typedef int                 chm_long;
*/

#define hv_set(hv, k, v)    hv_store(hv, k, strlen(k), v, 0)

typedef struct chmFile *    PCHMFILE;
typedef struct chmUnitInfo *PCHMUNITINFO;

static SV *mortal_pv(void *ptr) {
    SV *mortal = sv_2mortal(newSViv(0));
    sv_setref_pv(mortal, Nullch, ptr);
    return mortal;
}

static int
_chm_enumerator(PCHMFILE h, PCHMUNITINFO ui, SV **recall) {
    SV *cb;
    SV *context;
    int ret;
    dSP;
    cb = recall[0];
    context = recall[1];
    PUSHMARK(SP);
        XPUSHs(mortal_pv(h));
        XPUSHs(mortal_pv(ui));
        XPUSHs(context);
    PUTBACK;
        if (call_sv(cb, G_SCALAR) != 1)
            croak("the enumerator should return a scalar value");
    SPAGAIN;
        ret = POPi;
    PUTBACK;
    return ret;
}

#line 56 "libchm.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 200 "libchm.c"

/* INCLUDE:  Including 'const-xs.inc' from 'libchm.xs' */


XS_EUPXS(XS_cmt__libchm_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv = 0; /* avoid uninit var warning */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 225 "libchm.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid cmt::libchm macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined cmt::libchm macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 2);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing cmt::libchm macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 303 "libchm.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'libchm.xs' from 'const-xs.inc' */


XS_EUPXS(XS_cmt__libchm_chm_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_open)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filename");
    {
	const char *	filename = (const char *)SvPV_nolen(ST(0))
;
	PCHMFILE	RETVAL;
#line 55 "libchm.xs"
        RETVAL = chm_open(filename);
#line 325 "libchm.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, Nullch, (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_chm_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_close)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "h");
    {
	PCHMFILE	h;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_close",
			"h")
;
#line 64 "libchm.xs"
        chm_close(h);
#line 357 "libchm.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_cmt__libchm_chm_set_param); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_set_param)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "h, paramType, paramVal");
    {
	PCHMFILE	h;
	int	paramType = (int)SvIV(ST(1))
;
	int	paramVal = (int)SvIV(ST(2))
;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_set_param",
			"h")
;
#line 73 "libchm.xs"
        chm_set_param(h, paramType, paramVal);
#line 387 "libchm.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_cmt__libchm_chm_resolve_object); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_resolve_object)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "h, objPath, ui");
    {
	PCHMFILE	h;
	const char *	objPath = (const char *)SvPV_nolen(ST(1))
;
	PCHMUNITINFO	ui;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_resolve_object",
			"h")
;

	if (SvROK(ST(2))) {
	    IV tmp = SvIV((SV*)SvRV(ST(2)));
	    ui = INT2PTR(PCHMUNITINFO,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_resolve_object",
			"ui")
;
#line 82 "libchm.xs"
        RETVAL = chm_resolve_object(h, objPath, ui);
#line 428 "libchm.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_chm_retrieve_object); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_retrieve_object)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "h, ui, addr, len");
    {
	PCHMFILE	h;
	PCHMUNITINFO	ui;
	unsigned long	addr = (unsigned long)SvUV(ST(2))
;
	long	len = (long)SvIV(ST(3))
;
	SV *	RETVAL;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_retrieve_object",
			"h")
;

	if (SvROK(ST(1))) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    ui = INT2PTR(PCHMUNITINFO,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_retrieve_object",
			"ui")
;
#line 94 "libchm.xs"
        unsigned char *_buf;
        int cb;
#line 472 "libchm.c"
#line 97 "libchm.xs"
        _buf = (unsigned char *)malloc((size_t) len);
        /* assert _buf */
        cb = chm_retrieve_object(h, ui, _buf,
            (LONGUINT64) addr, (LONGINT64) len);
        RETVAL = newSVpvn(_buf, cb);
        free(_buf);
#line 480 "libchm.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_chm_enumerate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_enumerate)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "h, what, cb, context");
    {
	PCHMFILE	h;
	int	what = (int)SvIV(ST(1))
;
	SV *	cb = ST(2)
;
	SV *	context = ST(3)
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_enumerate",
			"h")
;
#line 114 "libchm.xs"
        SV *recall[2];
#line 516 "libchm.c"
#line 116 "libchm.xs"
        /* chm_enumerate(h, what, ENUM, context); */
        recall[0] = cb;
        recall[1] = context;
        RETVAL = chm_enumerate(h, what,
            (CHM_ENUMERATOR)_chm_enumerator, recall);
#line 523 "libchm.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_chm_enumerate_dir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_chm_enumerate_dir)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "h, prefix, what, cb, context");
    {
	PCHMFILE	h;
	const char *	prefix = (const char *)SvPV_nolen(ST(1))
;
	int	what = (int)SvIV(ST(2))
;
	SV *	cb = ST(3)
;
	SV *	context = ST(4)
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    h = INT2PTR(PCHMFILE,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::chm_enumerate_dir",
			"h")
;
#line 133 "libchm.xs"
        SV *recall[2];
#line 560 "libchm.c"
#line 135 "libchm.xs"
        /* chm_enumerate_dir(h, prefix, what, cb, context) */
        recall[0] = cb;
        recall[1] = context;
        RETVAL = chm_enumerate_dir(h, prefix, what,
            (CHM_ENUMERATOR)_chm_enumerator, recall);
#line 567 "libchm.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_dumpUnitInfo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_dumpUnitInfo)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ui");
    {
	PCHMUNITINFO	ui;
	HV *	RETVAL;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    ui = INT2PTR(PCHMUNITINFO,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::dumpUnitInfo",
			"ui")
;
#line 148 "libchm.xs"
        HV *hash;
#line 595 "libchm.c"
#line 150 "libchm.xs"
        hash = newHV();
        hv_set(hash, "start",   newSVuv((unsigned long) ui->start));
        hv_set(hash, "length",  newSVuv((unsigned long) ui->length));
        hv_set(hash, "space",   newSVuv((long) ui->space));
        hv_set(hash, "flags",   newSVuv((long) ui->flags));
        hv_set(hash, "path",    newSVpv(ui->path, 0));
        RETVAL = hash;
#line 604 "libchm.c"
	{
	    SV * RETVALSV;
	    RETVALSV = newRV((SV*)RETVAL);
	    RETVALSV = sv_2mortal(RETVALSV);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_cmt__libchm_getUnitInfo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_cmt__libchm_getUnitInfo)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ui");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	PCHMUNITINFO	ui;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    ui = INT2PTR(PCHMUNITINFO,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"cmt::libchm::getUnitInfo",
			"ui")
;
#line 165 "libchm.xs"
        XPUSHs(sv_2mortal(newSVpv(ui->path, 0)));
        XPUSHs(newSVuv((long) ui->flags));
        XPUSHs(newSVuv((unsigned long) ui->start));
        XPUSHs(newSVuv((unsigned long) ui->length));
        XPUSHs(newSVuv((long) ui->space));
#line 642 "libchm.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_cmt__libchm); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_cmt__libchm)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("cmt::libchm::constant", XS_cmt__libchm_constant);
        (void)newXSproto_portable("cmt::libchm::chm_open", XS_cmt__libchm_chm_open, file, "$");
        (void)newXSproto_portable("cmt::libchm::chm_close", XS_cmt__libchm_chm_close, file, "$");
        (void)newXSproto_portable("cmt::libchm::chm_set_param", XS_cmt__libchm_chm_set_param, file, "$$$");
        (void)newXSproto_portable("cmt::libchm::chm_resolve_object", XS_cmt__libchm_chm_resolve_object, file, "$$$");
        (void)newXSproto_portable("cmt::libchm::chm_retrieve_object", XS_cmt__libchm_chm_retrieve_object, file, "$$;$$");
        (void)newXSproto_portable("cmt::libchm::chm_enumerate", XS_cmt__libchm_chm_enumerate, file, "$$&;$");
        (void)newXSproto_portable("cmt::libchm::chm_enumerate_dir", XS_cmt__libchm_chm_enumerate_dir, file, "$$$&;$");
        (void)newXSproto_portable("cmt::libchm::dumpUnitInfo", XS_cmt__libchm_dumpUnitInfo, file, "$");
        (void)newXSproto_portable("cmt::libchm::getUnitInfo", XS_cmt__libchm_getUnitInfo, file, "$");
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

