#! /bin/sh
# chkconfig: 2345 20 80
# description: shendun-ef init

### BEGIN INIT INFO
# Provides:          sdefinit
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: shendun-ef init
# Description:       shendun-ef init
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sysdir=/proc/sys

case "$1" in
    start|restart|reload|force-reload)
        sdefpoll -r
        ;;

    stop)
        ;;

    status)
        if [ -f /var/run/sdefauth ]; then
            echo "Initialized"
        else
            echo "Not initialized yet"
        fi
        ;;
      
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac

