#!/bin/bash
    : ${MAIN:=`which main`}

    script=$(readlink -f "$0")
    project_dir="${script%/*}"

    mainopts=()
    appopts=()

    opt_debug=0
    opt_verbose=0

    while true; do
        case "$1" in
            -d)
                opt_debug=1
                shift
                continue
                ;;
            -v)
                opt_verbose=1
                mainopts=("${mainopts[@]}" -v)
                appopts=("${appopts[@]}" -v)
                shift
                continue
                ;;
        esac
        break
    done

    mainopts=("${mainopts[@]}" -r "$project_dir")

    if [ "$opt_debug" = 1 ]; then
        mainopts=("${mainopts[@]}" -O -Dpolyglot.inspect=localhost:9229)
        mainopts=("${mainopts[@]}" -O -Dpolyglot.inspect.Secure=false)
    fi

    if [ "$opt_verbose" -gt 0 ]; then
        echo $MAIN "${mainopts[@]}" CatMe "${appopts[@]}" "$@"
    fi
    $MAIN "${mainopts[@]}" CatMe "${appopts[@]}" "$@"

