#!/bin/bash
    : ${RCSID:=$Id: - @VERSION@ @DATE@ @TIME@ - $}
    : ${PACKAGE:=@PACKAGE@}
    : ${PROGRAM_TITLE:=}
    : ${PROGRAM_SYNTAX:=[OPTIONS] [--] ...}

    MAIN=`which main`

    . shlib
    import cliboot
    import findabc

    . /usr/share/bash-alias/aliases/cooltask.sh
    sqldir=`findcont %cooltask job cam19 sql`
    _log2 "sql dir: $sqldir"

    files=( $sqldir/dummy.sql )

    if [ "$1" == '-d' ]; then
        shift
        opt_debug=1
    fi

    mainopts=()

    if [ "$opt_debug" = 1 ]; then
        mainopts=("${mainopts[@]}" -O -Dpolyglot.inspect=localhost:9229)
        mainopts=("${mainopts[@]}" -O -Dpolyglot.inspect.Secure=false)
    fi

    echo $MAIN "${mainopts[@]}" CatMe "$@" "${files[@]}"
    $MAIN "${mainopts[@]}" CatMe "$@" "${files[@]}"

