#!/bin/bash
    RCSID='$Id$'
# $Revision$
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"
    . shlib-import cliboot

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] SVN push branches"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] <branch-name | url>"
    echo
    echo "Options: "
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    # find ancestor rev. of (cwd, named-branch)
    if [ -z "$1" ]; then
        help; exit
    fi
    branch="$1"
}

boot "$@"
