#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 2141 2010-12-13 06:15:26Z lenik $'
    short_opts="rhqv"
    long_opts="reformat,help,quiet,verbose,version"

    reformat=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Vim thru xml2/2xml"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] FILES"
    echo
    echo "Options: "
    echo "    -r, --reformat          Reformat after xml2/2xml transforms"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -r|--reformat)
            reformat=1;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    tmp=`tempfile`
    for f in "$@"; do
        xml2 <"$f" >$tmp
        if vi $tmp; then
            if [ "$reformat" = 1 ]; then
                2xml <$tmp | xmlindent -f -nbe >"$f"
            else
                2xml <$tmp >"$f"
            fi
        fi
    done
}

boot "$@"
