#!/bin/bash

echo Startup Lapiota $LAPIOTA_VER

for f in /lapiota/etc/startup.d/*.sh ~/etc/startup.d/*.sh; do
    echo "${f##*/} $f"
done | sort >/tmp/startup.lst

while read _ file; do
    read _CC title <$file
    echo -ne "[load] $title...\r"
    if . "$file"; then
        echo [done]
    else
        echo [fail]
    fi
done </tmp/startup.lst

TITLE="Successful booted, you may press ENTER to quit."
echo $TITLE
    cmd /c title $TITLE
TIMEOUT=3
while [ $TIMEOUT -gt 0 ]; do
    echo -ne "Auto quit... $TIMEOUT\\r"
    TIMEOUT=$((TIMEOUT - 1))
    if read -t 1 -n 1; then break; fi
done
