#!/usr/bin/perl

use strict;
use Encode("decode");
use Encode::Locale;
use URI::Encode;

my $encoder = URI::Encode->new({
        encode_reserved => 0
    });

for (@ARGV) {
    $_ = decode(locale => $_);
    print $encoder->decode($_) . "\n";
}
