#!/bin/bash

# (the default dash also support ## substitution).
THIS=${0##*/}
if [ "$THIS" = "coolvims" ]; then
    SUDO=sudo
else
    SUDO=
fi

VIM=vim

if [ -z "$1" ]; then
    $VIM
    exit $?
fi

for f in "$@"; do

    launcher=
    if [ ! -f "$f" ]; then
        if which=`which "$f"`; then
            f="$which"
        else
            fdir=`dirname "$f"`
            if [ ! -w "$fdir" ]; then
                launcher=$SUDO
            fi
            # create a new file, maybe
            $launcher $VIM "$f"
            continue
        fi
    fi

    tabrc=`guesstab "$f"`
    if [ ! -w "$f" ]; then
        launcher=$SUDO
    fi
    $launcher $VIM -c "$tabrc" "$f"

done
