#!/bin/bash

# (the default dash also support ## substitution).
THIS=${0##*/}
if [ "$THIS" = "coolvims" ]; then
    SUDO=sudo
else
    SUDO=
fi

if [ -z "$vim" ]; then
    vim=vim
fi

vimopts=()
nvimopts=0

if [ -z "$1" ]; then
    if [ -f .vimrc ]; then
        vimopts[nvimopts++]=-S
        vimopts[nvimopts++]=.vimrc
    fi
    $vim "${vimopts[@]}"
    exit $?
fi

for f in "$@"; do

    sudo_r=
    sudo_w=
    new_file=

    if [ ! -f "$f" ]; then

        # find exec-PATH if file isn't exist.
        if which=`which "$f"`; then
            f="$which"

        # or create a new file, when necessary
        else
            new_file=1
        fi
    fi

    fdir=`dirname "$f"`
    if [ -f "$fdir/.vimrc" ]; then
        vimopts[nvimopts++]=-S
        vimopts[nvimopts++]="$fdir/.vimrc"
    fi

    tabrc=
    if [ "$new_file" = 1 ]; then
        if [ ! -w "$fdir" ]; then
            sudo_w=$SUDO
        fi
    else
        if [ ! -r "$f" ]; then sudo_r=$SUDO; fi
        if [ ! -w "$f" ]; then sudo_w=$SUDO; fi
        tabrc=`$sudo_r guesstab "$f"`
    fi

    $sudo_w $vim "${vimopts[@]}" -c "$tabrc" "$f"

done
