#!/bin/bash

istmp=0

if [ -z "$1" ]; then
    in=`tempfile`
    cat >"$in"
    istmp=1
else
    in="$1"
fi

if [ ! -r "$in" ]; then
    echo "Could not read from $in"
fi

hastab=0
hasspace=0

TAB=$'\T'
SPACE=' '

if egrep -q "^$SPACE*$TAB" $in; then hastab=1; fi
if egrep -q "^$TAB*$SPACE" $in; then hasspace=1; fi

if [ $istmp = 1 ]; then rm -f "$in"; fi

if [ $hastab = 1 ]; then
    if [ $hasspace = 1 ]; then
        expandtab=1
        tabsize=8
        indent=4
    else
        expandtab=0
        tabsize=4
        indent=4
    fi
else
    expandtab=1
    tabsize=4
    indent=4
fi

mode=vi
case "$mode" in
vi)
    echo -n ":set"
    if [ $expandtab = 1 ]; then
        echo -n " expandtab"
    else
        echo -n " noexpandtab"
    fi
    echo -n " tabstop=$tabsize"
    echo -n " shiftwidth=$indent"
    echo
    ;;
*)
    echo "expandtab=$expandtab"
    echo "tabsize=$tabsize"
    echo "indent=$indent"
    ;;
esac
