.\"
.\"
.\" cideb.man - cideb manpage
.\" Copyright (C) 2010 Lenik (谢继雷)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH CIDEB 1
.SH NAME
cideb \- Build Debian package for distribute and commit.
.SH SYNOPSIS
.B cideb

.SH DESCRIPTION
cideb rebuild the Debian package by debuild, with version increased when
apropriate.  The version management is done through autover and autotools,
reconfiguration to the Makefiles is automaticlly done by autover.

The commit field of the version is increased by 1, so the Debian build
number is reset to 1 each time cideb is invoked.  The Debian changelog
is automaticlly updated by dh_incr utility, which in turns call into
autover to get the current version string.
The environment variable DEBFULLNAME and DEBEMAIL is used to fill in
the new changelog entry, and the corresponding GnuPG key is used to sign
the result files.

The built .deb archives are uploaded to dlocal host section defined in
/etc/dput.cf, by default it's located at /var/lib/dlocal which is initialized
by -dlocal package.  An apt update and dist-upgrade process is launched after
dput is done.

If everything goes well, a final SVN Commit is invoked, the clean build should
always be checked in because the changelog isn't mandatory in -cooldeb policy.

.SH EXAMPLES

.B
cideb
.PP
Run the BDUC (build/distrib/upgrade/commit) process.

.SH ENVIRONMENT

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the author.

.SH AUTHORS
Lenik <lenik at bodz.net>
.br
