#!/bin/bash

if [ ! -f VERSION.av ]; then
    echo "Not an autover dir. "
    exit 1
fi

if svn-isclean; then
    echo "already updated"
    exit 0
fi

if svn st VERSION.av | grep -q '^M'; then
    echo "Version is already increased. "
else
    if svn st | grep -q '^[AD]'; then
        echo "Detected minor-level changes"
        vercomp -i minor >/dev/null
    else
        vercomp -i commit >/dev/null
    fi
fi

[ -f configure.ac ] && autover

if ! deb-redist -i; then
    echo debuild/redist failed.
    exit 1
fi

# don't update/commit in batch-mode.
if [ "$1" != "-b" ]; then
    sudo aptitude update
    # sudo apt-get update

    if ! sudo apt-get dist-upgrade --allow-unauthenticated; then
        echo "dist-upgrade failed, canceled. "
        exit 1
    fi

    SVN=`which svn`
    $SVN ci
fi

