#!/bin/bash
    RCSID='$Id: bash.sh 1427 2010-08-25 04:39:31Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"
    . /usr/lib/bash/cliboot

    for envf in ../../.env ../.env .env; do
        if [ -f $envf ]; then
            . $envf
        fi
    done

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Rebuild the .deb archive and dput if succeed"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] PACKAGE-DIR"
    echo
    echo "Options: "
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {

    if [ ! -f configure ]; then
        reconf=1
        if ! autoreconf2 -is; then
            exit 1
        fi
    fi

    if [ ! -f Makefile ]; then
        makelook=1
        if ! makelook; then
            exit 2
        fi
    fi

    # edit the changelog
    # if ! ver=`maketestvar PACKAGE_VERSION`; then
    #     echo "Don't know the version, no Makefile variable. " >&2
    #     exit 4
    # fi

    base="${PWD##*/}"
    src="$PWD"

    # symlink doesn't work for dch, which use abs path always.
    # pushd /tmp >/dev/null
    # ln -s "$src" $base
    # popd >/dev/null
    pushd .. >/dev/null
    dir_ver=`dir-ver $base`
    cd "$dir_ver"
    dch -d "Upstream updates, automatic package by deb-redist"
    cd ..
    dir-nover "$dir_ver"
    popd

    if ! debuild --no-tgz-check; then
        exit 3
    fi

    # xjl-cooldeb_0.1.5-1_all.deb
    dh_debname | while read debname; do
        echo "Dput $debname..."

        debfile=../$debname
        debfullname="${debfile%.deb}"
        debnover="${debfullname%_*}"

        for ch in "$debnover"_*.changes; do
            echo "Commit $ch"

            # swapox: remove "override entry" in stderr.
            swapox dput -f local "$ch" |
                swapox grep -v "override entry"
        done

        echo
    done

    if [ "$reconf" = 1 ]; then
        autounconf
    fi

    echo Done.
}

boot "$@"
