#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="e:w:i:d:E:W:I:D:hqv"
    long_opts="error:,warn:,info:,debug:,error-mode:,warn-mode:,info-mode:,debug-mode:,help,quiet,verbose,version"

    error_mode='\[\(ERROR\|FATAL\|错误\|异常\)'
     warn_mode='\[\(WARN\|WARNING\|警告\)'
     info_mode='\[\(INFO\|NOTICE\|信息\|通知\)'
    debug_mode='\[\(DEBUG\|XXX\|调试\|测试\)'

    error_fx='1;41'
     warn_fx='45'
     info_fx='1;34'
    debug_fx='2'

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Render logs with colors"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -e, --error=FX          ANSI escapes for error lines"
    echo "    -w, --warn=FX           ANSI escapes for warning lines"
    echo "    -i, --info=FX           ANSI escapes for info lines"
    echo "    -d, --debug=FX          ANSI escapes for debug lines"
    echo "    -E, --error-mode=MODE   Error pattern to match"
    echo "    -W, --warn-mode=MODE    Warn pattern to match"
    echo "    -I, --info-mode=MODE    Info pattern to match"
    echo "    -D, --debug-mode=MODE   Debug pattern to match"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -e|--error) error_fx="$2";;
        -w|--warn)  warn_fx="$2";;
        -i|--info)  info_fx="$2";;
        -d|--debug) debug_fx="$2";;
        -E|--error-mode) error_mode="$2";;
        -W|--warn-mode)  warn_mode="$2";;
        -I|--info-mode)  info_mode="$2";;
        -D|--debug-mode) debug_mode="$2";;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    sed \
        -e "s/^\(\($error_mode\).*\)$/[${error_fx}m\1[0m/i" \
        -e "s/^\(\($warn_mode\).*\)$/[${warn_fx}m\1[0m/i" \
        -e "s/^\(\($info_mode\).*\)$/[${info_fx}m\1[0m/i" \
        -e "s/^\(\($debug_mode\).*\)$/[${debug_fx}m\1[0m/i" \
        "$@"
}

boot "$@"
