#!/bin/bash

# strip (PREFIX)FILE(SUFFIX) prefix/suffix

prefix="__DISABLED_"
suffix=""

if [ "${0##*/}" = "disfile" ]; then
    mode=decorate
fi

if [ "$1" = "--" ]; then
    shift
else
    if [ "$1" = "-d" ]; then
        mode=decorate
        shift
    else
        mode=strip
    fi
fi

dirty=0

for file in "$@"; do

    dirname="${file%/*}"
    if [ "$dirname" = "$file" ]; then
        dirname=.
        basename="$file"
    else
        basename="${file##*/}"
    fi

    stripped="${basename#$prefix}"
    stripped="${stripped%$suffix}"
    decorated="$prefix$stripped$suffix"

    stripped_file="$dirname/$stripped"
    decorated_file="$dirname/$decorated"

    if [ $mode = strip ]; then
        if [ -f "$stripped_file" ]; then
            echo "Skipped already stripped file: $stripped_file"
            continue
        fi

        if [ ! -f "$decorated_file" ]; then
            echo "File doesn't exist: $decorated_file"
            exit 1
        fi

        if mv "$decorated_file" "$stripped_file"; then
            dirty=1
        fi

    else

        if [ -f "$decorated_file" ]; then
            echo "Skipped already decorated file: $decorated_file"
            continue
        fi

        if [ ! -f "$stripped_file" ]; then
            echo "File doesn't exist: $stripped_file"
            exit 1
        fi

        if mv "$stripped_file" "$decorated_file"; then
            dirty=1
        fi
    fi

done

if [ $dirty = 1 ]; then
    exit 0
else
    exit 1
fi
