#!/bin/bash
    RCSID='$Id: bash.sh 1427 2010-08-25 04:39:31Z lenik $'
    short_opts="i:EFGPhqv"
    long_opts="index,extended-regexp,fixed-strings,basic-regexp,perl-regexp,help,quiet,verbose,version"
    . /usr/lib/bash/cliboot

    index=1
    GREP=grep

    self_base="${0##*/}"
    self_nol="${self_base%l}"
    case "$self_nol" in
        grep)
            GREP=grep;;
        egrep)
            GREP=egrep;;
        fgrep)
            GREP=fgrep;;
    esac

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Grep and print the line number of first match"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -E, --extended-regexp   use egrep"
    echo "    -F, --fixed-strings     use fgrep"
    echo "    -G, --basic-regexp      use grep"
    echo "    -P, --perl-regexp       use pgrep"
    echo "    -<INDEX>"
    echo "    -i, --index=INDEX       match the INDEX occurence."
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -E|--extended-regexp)
            GREP="grep -E";;
        -F|--fixed-strings)
            GREP="grep -F";;
        -G|--basic-regexp)
            GREP="grep -G";;
        -P|--perl-regexp)
            GREP="grep -P";;
        -i|--index)
            index="$2";;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            numtest="${1#-}"
            if [ -n "$numtest" ] && [ -z "${numtest//[0-9]}" ]; then
                index="$numtest"
            else
                quit "invalid option: $1"
            fi
            ;;
    esac
}

function main() {
    if [ $# = 0 ]; then
        echo "No pattern specified. "
        help
        return 1
    fi

    line=`$GREP -bnm$index "$@" | headrm -$((index-1)) | cut -d: -f1`

    if [ -n "$line" ]; then
        echo $line
        return 0
    else
        return 1
    fi
}

boot "$@"
