#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id$'
    short_opts="s:hqv"
    long_opts="signal,help,quiet,verbose,version"

    SIGNAL=TERM

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Kill all processes in the list"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] LIST-FILE"
    echo
    echo "Options: "
    echo "    -s, --signal=SIGNAL     Send specific signal to process"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -s|--signal)
            SIGNAL="2";;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ "$#" = 0 ]; then
        set -- -
    fi

    for f in "$@"; do
        if [ "$f" = - ]; then
            f=/dev/stdin
        fi
        while read pid xxx; do
            if [ ! -d /proc/$pid ]; then # The process is no more existed
                continue
            fi
            read cmdline <"/proc/$pid/cmdline"
            _log1 "Kill pid=$pid"
            _log2 "    -> $cmdline"
            kill -s $SIGNAL $pid
        done
    done
}

boot "$@"
