#!/bin/bash

if [ $# -gt 0 ]; then
	while [ $# -gt 0 ]; do
		$0 <$1
		last=$?
		shift
	done
	exit $last
fi

while read spec file vfstype mntops freq passno _; do
	if [ -z $file ]; then
		:
	elif [ "${spec:0:1}" == '#' ]; then
		:
	elif [ ! -b $spec ]; then
		:
	elif ! mountpoint -q $file; then
		:
	elif [ $vfstype == 'swap' ]; then
		swapoff $spec
	else
		echo -n Unmounting $file "($spec)"...
		# don't umount $spec, because spec may mount on different files
		if umount $file; then
			echo OK!
		else
			echo Failed "($?)".
		fi
	fi
done
