alias C='LANG=C'
alias L='. loop 1'
alias M='m2chdir'
alias M+='m2release'
alias MDP='mvn deploy -fn -Dmaven.test.skip=true'
alias MIN='mvn install -fn -Dmaven.test.skip=true'
alias MPK='mvn package -fn -Dmaven.test.skip=true'
alias Q='qlog'
alias TP='cd-debian-package'
alias __cd='builtin cd'
alias __popd='builtin popd'
alias __pushd='builtin pushd'
alias _bg='. run-bg'
alias _dir='. cd-exec'
alias acp='apt-cache policy'
alias adb-install='adb install -rdg'
alias axel='axel -a'
alias bc='bc -l /usr/share/doc/bc/maths.b'
alias catt='xf-tree cat'
alias ccd='. cd-ls'
alias cd-alias='. cd-alias'
alias cd.='cd `readlink -f .`'
alias cd..='. cd..n'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cdd='. cd-ls'
alias cdf='. cd-first'
alias cdrun='clusterdock_run'
alias cdssh='clusterdock_ssh'
alias cdt='. cd-tree'
alias d='ls -oF -N --color --block-size="'\''1"'
alias d.='d -d'
alias dcon='vicontrol'
alias dd+='dd conv=notrunc'
alias dd++='dd conv=notrunc oflag=append'
alias decrypt='gpg --decrypt'
alias depc='dpatch-edit-patch -c'
alias dh_makever='. dh_make-autover --createorig'
alias du1='du --max-depth=1'
alias du2='du --max-depth=2'
alias dw='. d-which'
alias e='emacsclient -nc'
alias eachdeb='eachdir -rfdebian/control'
alias egrep='egrep --color=auto'
alias encrypt='gpg --encrypt'
alias fgrep='fgrep --color=auto'
alias gd='git delta'
alias gg='gitg'
alias gmt='git mergetool --tool=meld'
alias grep='grep --color=auto'
alias grep-svn='grep --exclude-dir .svn'
alias grh='git reset --hard'
alias griom='git rebase -i origin/master'
alias grv='git remote -v'
alias h='man'
alias hist='. history-histgram'
alias hist1='. history-histgram 1'
alias hist2='. history-histgram 2'
alias hist3='. history-histgram 3'
alias hm='htmldoc-man'
alias incr-major='vercomp -i major'
alias incr-minor='vercomp -i minor'
alias l='ls -alF -N --color --block-size="'\''1"'
alias lddw='ldd-which'
alias lesst='xf-tree less'
alias ls='ls --color=auto'
alias make='make -I /usr/include'
alias mam='man -Pmore'
alias md='mkdir'
alias mdp='mvn deploy'
alias min='mvn install'
alias mlk='makelook'
alias mpk='mvn package'
alias mr+='cd.x mvn release:perform'
alias mr-='cd.x mvn release:prepare'
alias mr0='cd.x mvn release:rollback'
alias mte='mvn test'
alias newaps='newdeb -aps'
alias od='od -t x1'
alias ps='COLUMNS=1000 ps fx'
alias pure='git pull --rebase'
alias rd='rmdir'
alias rebc='git rebase --continue'
alias reconf='autoreconf2 -is'
alias reinst='reconf && makelook && sudo make install && unconf'
alias reset-author='git commit --amend --reset-author -C HEAD'
alias rsync='rsync --progress'
alias sadu='sudo apt-get update; sudo apt-get dist-upgrade'
alias safi='sudo apt-fast install --allow-unauthenticated'
alias sagb='sudo apt-get build-dep --allow-unauthenticated'
alias sagc='sudo apt-get clean; sudo apt-get autoclean; sudo apt-get autoremove'
alias sagi='sudo apt-get install --allow-unauthenticated'
alias sagp='sudo apt-get purge'
alias sagr='sudo apt-get-reinstall2'
alias sagu='sudo apt-get remove'
alias sau='sudo apt-get update; sudo aptitude full-upgrade'
alias sdi='sudo dpkg -i'
alias sdr='sudo dpkg-reconfigure'
alias sign='gpg --sign'
alias susl='sort | uniq -c | sort -n | less -eir'
