#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 2141 2010-12-13 06:15:26Z lenik $'
    short_opts="thqv"
    long_opts="track,help,quiet,verbose,version"

    track=

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Prepare to chroot into root fs"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -t, --track             Enable tracking mount"
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -t|--track)
            track=-t;;
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    for image in "$@"; do
        mnt="${image%.*}"
        if [ "$mnt" = "$image" ]; then
            mnt="$image..mnt"
        fi

        _log1 "Mount $image"
        if ! mountfile $track "$image"; then
            echo "Failed to mount. " >&2
            exit 1
        fi

        _log1 "Copy network config files"
        cp -vf /etc/hosts       "$mnt/etc"
        cp -vf /etc/resolv.conf "$mnt/etc"

        _log1 "Mount transient filesystems"
        mount -t proc   none "$mnt/proc"
        mount -t sysfs  none "$mnt/sys"
        mount -t devpts none "$mnt/dev/pts"
    done
}

boot "$@"
