#!/bin/bash

for f in "$@"; do
    url=
    url_root=

    if [ "$f" = "${f/:\/\/}" ]; then
        while IFS=: read k v; do
            v="${v# }"
            case "$k" in
            URL)
                url="$v";;
            "Repository Root")
                url_root="$v";;
            esac
        done < <(LANC=C svn info)

        if [ -n "$url" ]; then
            if [ "${f:0:1}" = / ]; then
                f="$url_root$f"
            else
                f="$url/$f"
            fi
        fi
    fi

    svn export "$f"
done
