#!/bin/bash

if [ $# = 0 ]; then
    echo "You didn't specify a file"
    exit 1
fi

file="$1"
shift

if [ $# = 0 ]; then
    echo "You didn't specify what to do when file changed"
    exit 1
fi

dir="${file%/*}"
if [ "$dir" = "$file" ] ; then
    dir=.
fi

. settermtitle "$file => $*"

# Force the first iteration.
ver=0
lastdate=`stat -c%Y "$file"`
onmodify "$file" xxx $((ver++)) "$@"

while true; do

    # -CDR: some programs modify file by delete/create/rename methods.
    dnotify -so -MCDR "$dir" -e onmodify "$file" "$lastdate" $ver "$@"

    if [ ! -e "$file" ]; then
        continue
    fi

    date=`stat -c%Y "$file"`
    if [ "$lastdate" != "$date" ]; then
        ((ver++))
        lastdate="$date"
    fi
done
