#!/bin/bash

if [ $# -lt 2 ]; then
    echo "loop <interval> <cmd-line>..."
    false
else
    _interval="$1"
    shift

    _cmd=$1

    if _a=`alias $_cmd 2>/dev/null`; then
        _a="${_a#*=\'}"
        _a="${_a%\'}"
        _cmd="$_a"
    fi

    shift
    _index=0
    _pad='------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'

    while true; do
        ((_index++))

        _cols=`tput cols`
        _title="[42mLoop Iteration[47m $_index[m"
        _ntitle=$(( ${#_title} + 2 - 13 ))
        _halfpad=$(( (_cols - _ntitle) / 2 ))
        _line="${_pad:0:_halfpad} $_title ${_pad:0:_cols - _ntitle - _halfpad}"
        echo "$_line"

        $_cmd "$@"

        echo "${_pad:0:_cols}"
        sleep $_interval
    done
fi

