#!/usr/bin/env perl

# subst: value -> keyword

use strict;
use warnings;
use cmt::subst;
use Getopt::Long;

GetOptions('color|c!' => \$opt_color);

subst_init();

my @substed;
for (@ARGV) {
    my $a = rsubst($_);
    push @substed, $a;
}

print join('   ', @substed)."\n";
