#!/usr/bin/env perl

# subst: keyword -> value

use strict;
use warnings;
use cmt::subst;

subst_init();

my $index = 0;
my $ch = 0;

for (@ARGV) {
    print ' ' if $index++;

    my $a = subst($_);
    $ch++ if $a ne $_;
    print $a;
}

print "\n";

# return 1 if no change.
exit($ch == 0);
