#!/usr/bin/env perl

use strict;
use warnings;
use cmt::subst;

subst_init();

my @substed;
for (@ARGV) {
    my $a = subst($_);
    push @substed, $_;
}

# print join('   ', @substed)."\n";
exec @substed;
