#!/bin/bash

cat control.in >debian/control

shopt -s globstar nullglob

tags=($( grep -h Section: ../../**/debian/control | cut -d: -f2 | sort | uniq ))

for tag in "${tags[@]}"; do
    echo "Scan $tag packages"

    cat <<EOM >>debian/control
Package: coolset-$tag
Architecture: all
Description: Lenik's cool $tag tools.
    This package brings Lenik's cool $tag tools to you.
Recommends:
EOM

    grep --include=tags -l $tag -r ../.. \
        | grep /debian/tags \
        | grep -v /all/ \
        | cut -d/ --complement -f -3 \
        | cut -d/ -f1 \
        | sort \
        | sed -e 's/^/    /' -e '$q;s/$/,/' \
        >>debian/control

    echo >>debian/control

done
